import Foundation

// GENERATED from ../../src/data/quotes.ts by scripts/sync-widget-quotes.mjs —
// do not edit by hand, run that script again after changing the dataset.
// The widget process can't import JS, so today's quote is computed
// independently here from the same month/day mapping.

struct DailyQuote {
    let month: Int
    let day: Int
    let en: String
    let author: String
}

enum QuoteStore {
    static let quotes: [DailyQuote] = [
        DailyQuote(month: 1, day: 1, en: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
        DailyQuote(month: 1, day: 2, en: "Well begun is half done.", author: "Aristotle"),
        DailyQuote(month: 1, day: 3, en: "Fall seven times, stand up eight.", author: "Japanese Proverb"),
        DailyQuote(month: 1, day: 4, en: "Whether you think you can, or you think you can't, you're right.", author: "Henry Ford"),
        DailyQuote(month: 1, day: 5, en: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
        DailyQuote(month: 1, day: 6, en: "A journey of a thousand miles begins with a single step.", author: "Laozi"),
        DailyQuote(month: 1, day: 7, en: "Rome wasn't built in a day.", author: "English Proverb"),
        DailyQuote(month: 1, day: 8, en: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 9, en: "Little strokes fell great oaks.", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 10, en: "No pain, no gain.", author: "English Proverb"),
        DailyQuote(month: 1, day: 11, en: "Knowledge is power.", author: "Francis Bacon"),
        DailyQuote(month: 1, day: 12, en: "The unexamined life is not worth living.", author: "Socrates"),
        DailyQuote(month: 1, day: 13, en: "Patience is bitter, but its fruit is sweet.", author: "Aristotle"),
        DailyQuote(month: 1, day: 14, en: "Little by little, a little becomes a lot.", author: "African Proverb"),
        DailyQuote(month: 1, day: 15, en: "Well done is better than well said.", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 16, en: "The palest ink is better than the best memory.", author: "Chinese Proverb"),
        DailyQuote(month: 1, day: 17, en: "A smooth sea never made a skilled sailor.", author: "English Proverb"),
        DailyQuote(month: 1, day: 18, en: "Diligence is the mother of good luck.", author: "Proverb"),
        DailyQuote(month: 1, day: 19, en: "Tomorrow belongs to those who prepare for it today.", author: "African Proverb"),
        DailyQuote(month: 1, day: 20, en: "He who hesitates is lost.", author: "English Proverb"),
        DailyQuote(month: 1, day: 21, en: "Constant dripping wears away the stone.", author: "Latin Proverb"),
        DailyQuote(month: 1, day: 22, en: "Where there is a will, there is a way.", author: "English Proverb"),
        DailyQuote(month: 1, day: 23, en: "Every master was once a beginner.", author: "Proverb"),
        DailyQuote(month: 1, day: 24, en: "The first step is always the hardest.", author: "French Proverb"),
        DailyQuote(month: 1, day: 25, en: "Better late than never.", author: "English Proverb"),
        DailyQuote(month: 1, day: 26, en: "A little learning is a dangerous thing.", author: "Alexander Pope"),
        DailyQuote(month: 1, day: 27, en: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison"),
        DailyQuote(month: 1, day: 28, en: "Success is the sum of small efforts, repeated day after day.", author: "Proverb"),
        DailyQuote(month: 1, day: 29, en: "He that can have patience can have what he will.", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 30, en: "Nothing is impossible to a willing heart.", author: "English Proverb"),
        DailyQuote(month: 1, day: 31, en: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius"),
        DailyQuote(month: 2, day: 1, en: "A room without books is like a body without a soul.", author: "Cicero"),
        DailyQuote(month: 2, day: 2, en: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb"),
        DailyQuote(month: 2, day: 3, en: "A kind word is like a spring day.", author: "Russian Proverb"),
        DailyQuote(month: 2, day: 4, en: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop"),
        DailyQuote(month: 2, day: 5, en: "A friend to all is a friend to none.", author: "Aristotle"),
        DailyQuote(month: 2, day: 6, en: "Two heads are better than one.", author: "Proverb"),
        DailyQuote(month: 2, day: 7, en: "A candle loses nothing by lighting another candle.", author: "Proverb"),
        DailyQuote(month: 2, day: 8, en: "Iron sharpens iron.", author: "Proverb"),
        DailyQuote(month: 2, day: 9, en: "A true friend is the greatest of all blessings.", author: "François de La Rochefoucauld"),
        DailyQuote(month: 2, day: 10, en: "Shared joy is a double joy; shared sorrow is half a sorrow.", author: "Swedish Proverb"),
        DailyQuote(month: 2, day: 11, en: "A single arrow is easily broken, but not ten in a bundle.", author: "Japanese Proverb"),
        DailyQuote(month: 2, day: 12, en: "United we stand, divided we fall.", author: "Aesop"),
        DailyQuote(month: 2, day: 13, en: "Honesty is the best policy.", author: "English Proverb"),
        DailyQuote(month: 2, day: 14, en: "Love truth, but pardon error.", author: "Voltaire"),
        DailyQuote(month: 2, day: 15, en: "A good friend is a connection to life.", author: "Proverb"),
        DailyQuote(month: 2, day: 16, en: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson"),
        DailyQuote(month: 2, day: 17, en: "Walk beside me and be my friend.", author: "Native American Proverb"),
        DailyQuote(month: 2, day: 18, en: "It is not the length of life, but the depth of life.", author: "Ralph Waldo Emerson"),
        DailyQuote(month: 2, day: 19, en: "Curiosity is the compass of the mind.", author: "Proverb"),
        DailyQuote(month: 2, day: 20, en: "He who asks a question is a fool for five minutes; he who does not ask remains a fool forever.", author: "Chinese Proverb"),
        DailyQuote(month: 2, day: 21, en: "Study the past if you would define the future.", author: "Confucius"),
        DailyQuote(month: 2, day: 22, en: "Learning never exhausts the mind.", author: "Leonardo da Vinci"),
        DailyQuote(month: 2, day: 23, en: "I know that I know nothing.", author: "Socrates"),
        DailyQuote(month: 2, day: 24, en: "To teach is to learn twice.", author: "Joseph Joubert"),
        DailyQuote(month: 2, day: 25, en: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle"),
        DailyQuote(month: 2, day: 26, en: "Every day is a chance to become better.", author: "Proverb"),
        DailyQuote(month: 2, day: 27, en: "Wisdom begins in wonder.", author: "Socrates"),
        DailyQuote(month: 2, day: 28, en: "He who knows others is wise; he who knows himself is enlightened.", author: "Laozi"),
        DailyQuote(month: 3, day: 1, en: "He who has a why to live can bear with almost any how.", author: "Nietzsche"),
        DailyQuote(month: 3, day: 2, en: "He conquers who endures.", author: "Persius"),
        DailyQuote(month: 3, day: 3, en: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius"),
        DailyQuote(month: 3, day: 4, en: "Patience is the key to relief.", author: "Arabic Proverb"),
        DailyQuote(month: 3, day: 5, en: "Luck is what happens when preparation meets opportunity.", author: "Seneca"),
        DailyQuote(month: 3, day: 6, en: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus"),
        DailyQuote(month: 3, day: 7, en: "A good laugh and a long sleep are the best cures.", author: "Irish Proverb"),
        DailyQuote(month: 3, day: 8, en: "The secret of getting ahead is getting started.", author: "Mark Twain"),
        DailyQuote(month: 3, day: 9, en: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau"),
        DailyQuote(month: 3, day: 10, en: "Habits are first cobwebs, then cables.", author: "Spanish Proverb"),
        DailyQuote(month: 3, day: 11, en: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman"),
        DailyQuote(month: 3, day: 12, en: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott"),
        DailyQuote(month: 3, day: 13, en: "No one is useless in this world who lightens the burdens of another.", author: "Charles Dickens"),
        DailyQuote(month: 3, day: 14, en: "There is nothing I would not do for those who are really my friends.", author: "Jane Austen"),
        DailyQuote(month: 3, day: 15, en: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo"),
        DailyQuote(month: 3, day: 16, en: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy"),
        DailyQuote(month: 3, day: 17, en: "To go wrong in one's own way is better than to go right in someone else's.", author: "Fyodor Dostoevsky"),
        DailyQuote(month: 3, day: 18, en: "Act as if what you do makes a difference. It does.", author: "Immanuel Kant"),
        DailyQuote(month: 3, day: 19, en: "Whatever you can do, or dream you can, begin it.", author: "Johann Wolfgang von Goethe"),
        DailyQuote(month: 3, day: 20, en: "Victory belongs to the most persevering.", author: "Napoleon Bonaparte"),
        DailyQuote(month: 3, day: 21, en: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale"),
        DailyQuote(month: 3, day: 22, en: "Failure is impossible.", author: "Susan B. Anthony"),
        DailyQuote(month: 3, day: 23, en: "If there is no struggle, there is no progress.", author: "Frederick Douglass"),
        DailyQuote(month: 3, day: 24, en: "Success is measured not so much by the position one has reached, but by the obstacles overcome.", author: "Booker T. Washington"),
        DailyQuote(month: 3, day: 25, en: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
        DailyQuote(month: 3, day: 26, en: "The tree that does not bend with the wind will be broken by it.", author: "German Proverb"),
        DailyQuote(month: 3, day: 27, en: "Better a good friend than a bad relative.", author: "Danish Proverb"),
        DailyQuote(month: 3, day: 28, en: "One kind word can warm three winter months.", author: "Korean Proverb"),
        DailyQuote(month: 3, day: 29, en: "No matter how far you have gone on a wrong road, turn back.", author: "Turkish Proverb"),
        DailyQuote(month: 3, day: 30, en: "Better bend than break.", author: "Scottish Proverb"),
        DailyQuote(month: 3, day: 31, en: "There is no failure except in no longer trying.", author: "Elbert Hubbard"),
        DailyQuote(month: 4, day: 1, en: "The beginning is the most important part of the work.", author: "Plato"),
        DailyQuote(month: 4, day: 2, en: "Opportunities multiply as they are seized.", author: "Sun Tzu"),
        DailyQuote(month: 4, day: 3, en: "This above all: to thine own self be true.", author: "William Shakespeare"),
        DailyQuote(month: 4, day: 4, en: "It is better to offer no excuse than a bad one.", author: "George Washington"),
        DailyQuote(month: 4, day: 5, en: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson"),
        DailyQuote(month: 4, day: 6, en: "Whatever you are, be a good one.", author: "Abraham Lincoln"),
        DailyQuote(month: 4, day: 7, en: "Genius is eternal patience.", author: "Michelangelo"),
        DailyQuote(month: 4, day: 8, en: "If I have seen further, it is by standing on the shoulders of giants.", author: "Isaac Newton"),
        DailyQuote(month: 4, day: 9, en: "It is not the strongest of the species that survives, but the most adaptable to change.", author: "Charles Darwin"),
        DailyQuote(month: 4, day: 10, en: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie"),
        DailyQuote(month: 4, day: 11, en: "What comes from the heart, enters the heart.", author: "Jewish Proverb"),
        DailyQuote(month: 4, day: 12, en: "Ask the experienced rather than the learned.", author: "Persian Proverb"),
        DailyQuote(month: 4, day: 13, en: "A good beginning makes a good ending.", author: "Welsh Proverb"),
        DailyQuote(month: 4, day: 14, en: "He who does not advance, goes backward.", author: "Portuguese Proverb"),
        DailyQuote(month: 4, day: 15, en: "After the game, the king and the pawn go into the same box.", author: "Italian Proverb"),
        DailyQuote(month: 4, day: 16, en: "One who wants a rose must respect the thorn.", author: "Swiss Proverb"),
        DailyQuote(month: 4, day: 17, en: "A drop of patience is worth more than a bushel of brains.", author: "Dutch Proverb"),
        DailyQuote(month: 4, day: 18, en: "Do good and cast it into the sea.", author: "Indian Proverb"),
        DailyQuote(month: 4, day: 19, en: "Going through hardship is going through a school.", author: "Vietnamese Proverb"),
        DailyQuote(month: 4, day: 20, en: "A gem cannot be polished without friction, nor a person perfected without trials.", author: "Thai Proverb"),
        DailyQuote(month: 4, day: 21, en: "He who does not look back at where he came from will not reach his destination.", author: "Filipino Proverb"),
        DailyQuote(month: 4, day: 22, en: "He who chases two hares catches neither.", author: "Polish Proverb"),
        DailyQuote(month: 4, day: 23, en: "Happiness is a place between too little and too much.", author: "Finnish Proverb"),
        DailyQuote(month: 4, day: 24, en: "There is no such thing as bad weather, only bad clothes.", author: "Norwegian Proverb"),
        DailyQuote(month: 4, day: 25, en: "A book is a mute teacher.", author: "Icelandic Proverb"),
        DailyQuote(month: 4, day: 26, en: "Waste no more time arguing about what a good person should be. Be one.", author: "Marcus Aurelius"),
        DailyQuote(month: 4, day: 27, en: "Every new beginning comes from some other beginning's end.", author: "Seneca"),
        DailyQuote(month: 4, day: 28, en: "First say to yourself what you would be, and then do what you have to do.", author: "Epictetus"),
        DailyQuote(month: 4, day: 29, en: "While there's life, there's hope.", author: "Cicero"),
        DailyQuote(month: 4, day: 30, en: "Actions speak louder than words.", author: "English Proverb"),
        DailyQuote(month: 5, day: 1, en: "He has the most who is content with the least.", author: "Diogenes"),
        DailyQuote(month: 5, day: 2, en: "Educate the children and it won't be necessary to punish the men.", author: "Pythagoras"),
        DailyQuote(month: 5, day: 3, en: "Walking is the best medicine.", author: "Hippocrates"),
        DailyQuote(month: 5, day: 4, en: "Question everything.", author: "Euripides"),
        DailyQuote(month: 5, day: 5, en: "Wisdom outweighs any wealth.", author: "Sophocles"),
        DailyQuote(month: 5, day: 6, en: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch"),
        DailyQuote(month: 5, day: 7, en: "Nothing is stronger than habit.", author: "Ovid"),
        DailyQuote(month: 5, day: 8, en: "Seize the day, trusting little in tomorrow.", author: "Horace"),
        DailyQuote(month: 5, day: 9, en: "Home is where the heart is.", author: "Pliny the Elder"),
        DailyQuote(month: 5, day: 10, en: "The great man is he who does not lose his child's heart.", author: "Mencius"),
        DailyQuote(month: 5, day: 11, en: "Flow with whatever may happen and let your mind be free.", author: "Zhuangzi"),
        DailyQuote(month: 5, day: 12, en: "Today is victory over yourself of yesterday.", author: "Miyamoto Musashi"),
        DailyQuote(month: 5, day: 13, en: "If you want your dreams to come true, don't sleep.", author: "Yiddish Proverb"),
        DailyQuote(month: 5, day: 14, en: "When spider webs unite, they can tie up a lion.", author: "Ethiopian Proverb"),
        DailyQuote(month: 5, day: 15, en: "However long the night, the dawn will break.", author: "Nigerian Proverb"),
        DailyQuote(month: 5, day: 16, en: "What is the most important thing in the world? It is people, it is people, it is people.", author: "Maori Proverb"),
        DailyQuote(month: 5, day: 17, en: "Not all knowledge is found in one place.", author: "Hawaiian Proverb"),
        DailyQuote(month: 5, day: 18, en: "Tell me and I forget, teach me and I remember, involve me and I learn.", author: "Proverb"),
        DailyQuote(month: 5, day: 19, en: "Repetition is the mother of learning.", author: "Russian Proverb"),
        DailyQuote(month: 5, day: 20, en: "Old men plant trees whose shade they will never sit in.", author: "Greek Proverb"),
        DailyQuote(month: 5, day: 21, en: "The wise man keeps his tongue in his heart.", author: "Egyptian Proverb"),
        DailyQuote(month: 5, day: 22, en: "A book is like a garden carried in the pocket.", author: "Armenian Proverb"),
        DailyQuote(month: 5, day: 23, en: "A single spark can start a great fire.", author: "Mongolian Proverb"),
        DailyQuote(month: 5, day: 24, en: "Do not fix your eyes on the road behind others; look at your own road.", author: "Tibetan Proverb"),
        DailyQuote(month: 5, day: 25, en: "Because of a mistake, you learn something you did not know before.", author: "Malay Proverb"),
        DailyQuote(month: 5, day: 26, en: "Light burdens become heavy if carried far.", author: "Indonesian Proverb"),
        DailyQuote(month: 5, day: 27, en: "It is best to do things in the right order.", author: "Inuit Proverb"),
        DailyQuote(month: 5, day: 28, en: "He who wants to eat the kernel must crack the nut.", author: "Czech Proverb"),
        DailyQuote(month: 5, day: 29, en: "Practice makes the master.", author: "Hungarian Proverb"),
        DailyQuote(month: 5, day: 30, en: "Work praises the master.", author: "Bulgarian Proverb"),
        DailyQuote(month: 5, day: 31, en: "A guest is a gift, whether they come early or late.", author: "Georgian Proverb"),
        DailyQuote(month: 6, day: 1, en: "The heart has its reasons which reason does not know.", author: "Blaise Pascal"),
        DailyQuote(month: 6, day: 2, en: "It is not enough to have a good mind; the main thing is to use it well.", author: "René Descartes"),
        DailyQuote(month: 6, day: 3, en: "Common sense is not so common.", author: "Voltaire"),
        DailyQuote(month: 6, day: 4, en: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson"),
        DailyQuote(month: 6, day: 5, en: "Come forth into the light of things, let Nature be your teacher.", author: "William Wordsworth"),
        DailyQuote(month: 6, day: 6, en: "A thing of beauty is a joy forever.", author: "John Keats"),
        DailyQuote(month: 6, day: 7, en: "If winter comes, can spring be far behind?", author: "Percy Bysshe Shelley"),
        DailyQuote(month: 6, day: 8, en: "To strive, to seek, to find, and not to yield.", author: "Alfred Lord Tennyson"),
        DailyQuote(month: 6, day: 9, en: "Be yourself; everyone else is already taken.", author: "Oscar Wilde"),
        DailyQuote(month: 6, day: 10, en: "Knowledge is of no value unless you put it into practice.", author: "Anton Chekhov"),
        DailyQuote(month: 6, day: 11, en: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson"),
        DailyQuote(month: 6, day: 12, en: "It is never too late to be what you might have been.", author: "George Eliot"),
        DailyQuote(month: 6, day: 13, en: "Happiness, like a butterfly, may alight upon you if you sit quietly.", author: "Nathaniel Hawthorne"),
        DailyQuote(month: 6, day: 14, en: "Better to fail in originality than to succeed in imitation.", author: "Herman Melville"),
        DailyQuote(month: 6, day: 15, en: "I am no bird; and no net ensnares me; I am a free human being with an independent will.", author: "Charlotte Brontë"),
        DailyQuote(month: 6, day: 16, en: "Progress is the law of life.", author: "Elizabeth Barrett Browning"),
        DailyQuote(month: 6, day: 17, en: "Great minds have purposes, others have wishes.", author: "Washington Irving"),
        DailyQuote(month: 6, day: 18, en: "No man's knowledge here can go beyond his experience.", author: "John Locke"),
        DailyQuote(month: 6, day: 19, en: "Nature never deceives us; it is we who deceive ourselves.", author: "Jean-Jacques Rousseau"),
        DailyQuote(month: 6, day: 20, en: "Success in the majority of circumstances depends on knowing how long it takes to succeed.", author: "Montesquieu"),
        DailyQuote(month: 6, day: 21, en: "A book holds a house of gold.", author: "Chinese Proverb"),
        DailyQuote(month: 6, day: 22, en: "To know everything is to know nothing.", author: "French Proverb"),
        DailyQuote(month: 6, day: 23, en: "Listen or your tongue will make you deaf.", author: "Native American Proverb"),
        DailyQuote(month: 6, day: 24, en: "Fortune favors the bold.", author: "Latin Proverb"),
        DailyQuote(month: 6, day: 25, en: "Speak little, do much.", author: "Spanish Proverb"),
        DailyQuote(month: 6, day: 26, en: "The morning hour has gold in its mouth.", author: "German Proverb"),
        DailyQuote(month: 6, day: 27, en: "The clever man is not the one who gets out of a difficulty easily, but who does not get into it.", author: "Arabic Proverb"),
        DailyQuote(month: 6, day: 28, en: "It takes a village to raise a child.", author: "African Proverb"),
        DailyQuote(month: 6, day: 29, en: "Slow and steady wins the race.", author: "Aesop"),
        DailyQuote(month: 6, day: 30, en: "Practice what you preach.", author: "English Proverb"),
        DailyQuote(month: 7, day: 1, en: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton"),
        DailyQuote(month: 7, day: 2, en: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson"),
        DailyQuote(month: 7, day: 3, en: "All that we see or seem is but a dream within a dream.", author: "Edgar Allan Poe"),
        DailyQuote(month: 7, day: 4, en: "Great things are done when men and mountains meet.", author: "William Blake"),
        DailyQuote(month: 7, day: 5, en: "The best-laid schemes of mice and men often go awry.", author: "Robert Burns"),
        DailyQuote(month: 7, day: 6, en: "Vision is the art of seeing what is invisible to others.", author: "Jonathan Swift"),
        DailyQuote(month: 7, day: 7, en: "Fear of danger is ten thousand times more terrifying than danger itself.", author: "Daniel Defoe"),
        DailyQuote(month: 7, day: 8, en: "Advice is like snow; the softer it falls, the longer it dwells upon the mind.", author: "Samuel Taylor Coleridge"),
        DailyQuote(month: 7, day: 9, en: "If we had no winter, the spring would not be so pleasant.", author: "Anne Bradstreet"),
        DailyQuote(month: 7, day: 10, en: "He that is down needs fear no fall.", author: "John Bunyan"),
        DailyQuote(month: 7, day: 11, en: "Unity is strength, division is weakness.", author: "Swahili Proverb"),
        DailyQuote(month: 7, day: 12, en: "However far the stream flows, it never forgets its source.", author: "Yoruba Proverb"),
        DailyQuote(month: 7, day: 13, en: "A person is a person through other persons.", author: "Zulu Proverb"),
        DailyQuote(month: 7, day: 14, en: "No one shows a child the sky.", author: "Akan Proverb"),
        DailyQuote(month: 7, day: 15, en: "Rain does not fall on one roof alone.", author: "Somali Proverb"),
        DailyQuote(month: 7, day: 16, en: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "East African Proverb"),
        DailyQuote(month: 7, day: 17, en: "Do not compare your chapter one with someone else's chapter twenty.", author: "Nepali Proverb"),
        DailyQuote(month: 7, day: 18, en: "Do not throw away the ladder after you have climbed the wall.", author: "Sri Lankan Proverb"),
        DailyQuote(month: 7, day: 19, en: "A tree is known by its fruit.", author: "Bengali Proverb"),
        DailyQuote(month: 7, day: 20, en: "He who seeks, finds.", author: "Urdu Proverb"),
        DailyQuote(month: 7, day: 21, en: "Ask a wise question, get a wise answer.", author: "Afghan Proverb"),
        DailyQuote(month: 7, day: 22, en: "A friend's eye is a good mirror.", author: "Kurdish Proverb"),
        DailyQuote(month: 7, day: 23, en: "Even a small bee can sting a big bear.", author: "Azerbaijani Proverb"),
        DailyQuote(month: 7, day: 24, en: "Knowledge without practice is a tree without fruit.", author: "Kazakh Proverb"),
        DailyQuote(month: 7, day: 25, en: "A single tree does not make a forest.", author: "Uzbek Proverb"),
        DailyQuote(month: 7, day: 26, en: "Be humble, for you are made of earth. Be noble, for you are made of stars.", author: "Serbian Proverb"),
        DailyQuote(month: 7, day: 27, en: "Little children step on your toes; big children step on your heart.", author: "Croatian Proverb"),
        DailyQuote(month: 7, day: 28, en: "The apple doesn't fall far from the tree.", author: "Romanian Proverb"),
        DailyQuote(month: 7, day: 29, en: "Together we are strong; apart we are weak.", author: "Ukrainian Proverb"),
        DailyQuote(month: 7, day: 30, en: "Every path has its puddle.", author: "Slovenian Proverb"),
        DailyQuote(month: 7, day: 31, en: "A good word is like a spring rain.", author: "Slovak Proverb"),
        DailyQuote(month: 8, day: 1, en: "Chance favors the prepared mind.", author: "Louis Pasteur"),
        DailyQuote(month: 8, day: 2, en: "You can't wait for inspiration. You have to go after it with a club.", author: "Jack London"),
        DailyQuote(month: 8, day: 3, en: "Great is the art of beginning, but greater is the art of ending.", author: "Henry Wadsworth Longfellow"),
        DailyQuote(month: 8, day: 4, en: "Not failure, but low aim, is crime.", author: "James Russell Lowell"),
        DailyQuote(month: 8, day: 5, en: "The talent of success is nothing more than doing well what you can do.", author: "John Greenleaf Whittier"),
        DailyQuote(month: 8, day: 6, en: "Genius is only the power of making continuous efforts.", author: "William Cullen Bryant"),
        DailyQuote(month: 8, day: 7, en: "The first step to knowledge is to know that we are ignorant.", author: "Thomas Carlyle"),
        DailyQuote(month: 8, day: 8, en: "Quality is never an accident; it is always the result of intelligent effort.", author: "John Ruskin"),
        DailyQuote(month: 8, day: 9, en: "Have something to say, and say it as clearly as you can.", author: "Matthew Arnold"),
        DailyQuote(month: 8, day: 10, en: "The great aim of education is not knowledge but action.", author: "Herbert Spencer"),
        DailyQuote(month: 8, day: 11, en: "Act the way you'd like to be, and soon you'll be the way you act.", author: "William James"),
        DailyQuote(month: 8, day: 12, en: "Do your duty, and a little more, and the future will take care of itself.", author: "Andrew Carnegie"),
        DailyQuote(month: 8, day: 13, en: "Be ashamed to die until you have won some victory for humanity.", author: "Horace Mann"),
        DailyQuote(month: 8, day: 14, en: "Beyond the mountains, more mountains.", author: "Haitian Proverb"),
        DailyQuote(month: 8, day: 15, en: "Time longer than rope.", author: "Jamaican Proverb"),
        DailyQuote(month: 8, day: 16, en: "The shrimp that falls asleep is carried away by the current.", author: "Cuban Proverb"),
        DailyQuote(month: 8, day: 17, en: "The mountain does not come to you; you must go to the mountain.", author: "Peruvian Proverb"),
        DailyQuote(month: 8, day: 18, en: "However tired you may be, do not lean on a rotten stick.", author: "Mexican Proverb"),
        DailyQuote(month: 8, day: 19, en: "Speech is silver, but silence is golden.", author: "Punjabi Proverb"),
        DailyQuote(month: 8, day: 20, en: "Even a small ant can build a big anthill.", author: "Tamil Proverb"),
        DailyQuote(month: 8, day: 21, en: "Knowledge grows when it is shared.", author: "Gujarati Proverb"),
        DailyQuote(month: 8, day: 22, en: "It is easier to know how to speak than to know when to be silent.", author: "Burmese Proverb"),
        DailyQuote(month: 8, day: 23, en: "The buffalo that arrives first drinks the clean water.", author: "Cambodian Proverb"),
        DailyQuote(month: 8, day: 24, en: "The elephant's tusks cannot be hidden in its mouth.", author: "Lao Proverb"),
        DailyQuote(month: 8, day: 25, en: "Whoever wants makes progress; whoever does not want, offers excuses.", author: "Basque Proverb"),
        DailyQuote(month: 8, day: 26, en: "Only those who do nothing make no mistakes.", author: "Sicilian Proverb"),
        DailyQuote(month: 8, day: 27, en: "Everyone is the smith of their own fortune.", author: "Estonian Proverb"),
        DailyQuote(month: 8, day: 28, en: "Small deeds done are better than great deeds planned.", author: "Latvian Proverb"),
        DailyQuote(month: 8, day: 29, en: "He who wants to eat honey must brave the bee sting.", author: "Lithuanian Proverb"),
        DailyQuote(month: 8, day: 30, en: "A kind word is worth more than a rich gift.", author: "Belarusian Proverb"),
        DailyQuote(month: 8, day: 31, en: "Every cloud has a silver lining.", author: "English Proverb"),
        DailyQuote(month: 9, day: 1, en: "By three methods we may learn wisdom: first, by reflection; second, by imitation; third, by experience.", author: "Confucius"),
        DailyQuote(month: 9, day: 2, en: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", author: "Mark Twain"),
        DailyQuote(month: 9, day: 3, en: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau"),
        DailyQuote(month: 9, day: 4, en: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson"),
        DailyQuote(month: 9, day: 5, en: "Few things help an individual more than to place responsibility upon him, and to let him know that you trust him.", author: "Booker T. Washington"),
        DailyQuote(month: 9, day: 6, en: "Power concedes nothing without a demand. It never did and it never will.", author: "Frederick Douglass"),
        DailyQuote(month: 9, day: 7, en: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt"),
        DailyQuote(month: 9, day: 8, en: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci"),
        DailyQuote(month: 9, day: 9, en: "Genius is patience.", author: "Isaac Newton"),
        DailyQuote(month: 9, day: 10, en: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius"),
        DailyQuote(month: 9, day: 11, en: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca"),
        DailyQuote(month: 9, day: 12, en: "No man is free who is not master of himself.", author: "Epictetus"),
        DailyQuote(month: 9, day: 13, en: "To be ignorant of what happened before you were born is to be forever a child.", author: "Cicero"),
        DailyQuote(month: 9, day: 14, en: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle"),
        DailyQuote(month: 9, day: 15, en: "Courage is knowing what not to fear.", author: "Plato"),
        DailyQuote(month: 9, day: 16, en: "The way to gain a good reputation is to endeavor to be what you desire to appear.", author: "Socrates"),
        DailyQuote(month: 9, day: 17, en: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu"),
        DailyQuote(month: 9, day: 18, en: "We know what we are, but know not what we may be.", author: "William Shakespeare"),
        DailyQuote(month: 9, day: 19, en: "Judge a man by his questions rather than his answers.", author: "Voltaire"),
        DailyQuote(month: 9, day: 20, en: "Teachers open the door, but you must enter by yourself.", author: "Chinese Proverb"),
        DailyQuote(month: 9, day: 21, en: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese Proverb"),
        DailyQuote(month: 9, day: 22, en: "You can't judge a book by its cover.", author: "English Proverb"),
        DailyQuote(month: 9, day: 23, en: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb"),
        DailyQuote(month: 9, day: 24, en: "A wise man does not need advice, and a fool doesn't take it.", author: "Arabic Proverb"),
        DailyQuote(month: 9, day: 25, en: "Through hardships to the stars.", author: "Latin Proverb"),
        DailyQuote(month: 9, day: 26, en: "Little by little, the camel enters the couscous.", author: "Moroccan Proverb"),
        DailyQuote(month: 9, day: 27, en: "A stumble may prevent a fall.", author: "Lebanese Proverb"),
        DailyQuote(month: 9, day: 28, en: "The dogs bark, but the caravan moves on.", author: "Syrian Proverb"),
        DailyQuote(month: 9, day: 29, en: "The one who does not travel thinks their mother is the best cook.", author: "Rwandan Proverb"),
        DailyQuote(month: 9, day: 30, en: "The person who wakes up first, sees more of the day.", author: "Senegalese Proverb"),
        DailyQuote(month: 10, day: 1, en: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin"),
        DailyQuote(month: 10, day: 2, en: "Nothing can stop the man with the right mental attitude from achieving his goal.", author: "Thomas Jefferson"),
        DailyQuote(month: 10, day: 3, en: "I will prepare and someday my chance will come.", author: "Abraham Lincoln"),
        DailyQuote(month: 10, day: 4, en: "Actions, not words, are the true test of friendship.", author: "George Washington"),
        DailyQuote(month: 10, day: 5, en: "Better three hours too soon than a minute too late.", author: "William Shakespeare"),
        DailyQuote(month: 10, day: 6, en: "The greater danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.", author: "Michelangelo"),
        DailyQuote(month: 10, day: 7, en: "One never notices what has been done; one can only see what remains to be done.", author: "Marie Curie"),
        DailyQuote(month: 10, day: 8, en: "Appearances are often deceiving.", author: "Aesop"),
        DailyQuote(month: 10, day: 9, en: "A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success.", author: "Elbert Hubbard"),
        DailyQuote(month: 10, day: 10, en: "To play a wrong note is insignificant; to play without passion is inexcusable.", author: "Ludwig van Beethoven"),
        DailyQuote(month: 10, day: 11, en: "Nothing is too wonderful to be true.", author: "Michael Faraday"),
        DailyQuote(month: 10, day: 12, en: "Before anything else, preparation is the key to success.", author: "Alexander Graham Bell"),
        DailyQuote(month: 10, day: 13, en: "I am seeking, I am striving, I am in it with all my heart.", author: "Vincent van Gogh"),
        DailyQuote(month: 10, day: 14, en: "Children need models rather than critics.", author: "Joseph Joubert"),
        DailyQuote(month: 10, day: 15, en: "To err is human, to forgive divine.", author: "Alexander Pope"),
        DailyQuote(month: 10, day: 16, en: "Reading maketh a full man, conference a ready man, and writing an exact man.", author: "Francis Bacon"),
        DailyQuote(month: 10, day: 17, en: "Divide each difficulty into as many parts as is feasible.", author: "René Descartes"),
        DailyQuote(month: 10, day: 18, en: "A closed mouth catches no flies.", author: "Chinese Proverb"),
        DailyQuote(month: 10, day: 19, en: "The reputation of a thousand years may be determined by the conduct of one hour.", author: "Japanese Proverb"),
        DailyQuote(month: 10, day: 20, en: "Even monkeys fall from trees.", author: "Korean Proverb"),
        DailyQuote(month: 10, day: 21, en: "When eating fruit, remember who planted the tree.", author: "Vietnamese Proverb"),
        DailyQuote(month: 10, day: 22, en: "The one who plants a tree, plants hope.", author: "Proverb"),
        DailyQuote(month: 10, day: 23, en: "Happiness is a direction, not a destination.", author: "Bhutanese Proverb"),
        DailyQuote(month: 10, day: 24, en: "Better a diamond with a flaw than a pebble without one.", author: "Bosnian Proverb"),
        DailyQuote(month: 10, day: 25, en: "He who does not know how to smile should not open a shop.", author: "Macedonian Proverb"),
        DailyQuote(month: 10, day: 26, en: "The wolf changes his coat, but not his character.", author: "Albanian Proverb"),
        DailyQuote(month: 10, day: 27, en: "A good neighbor is better than a distant friend.", author: "Cypriot Proverb"),
        DailyQuote(month: 10, day: 28, en: "Little said, soon mended.", author: "Maltese Proverb"),
        DailyQuote(month: 10, day: 29, en: "Every beginning is hard.", author: "Austrian Proverb"),
        DailyQuote(month: 10, day: 30, en: "Small rain lays great dust.", author: "Belgian Proverb"),
        DailyQuote(month: 10, day: 31, en: "Time teaches more than a wise man.", author: "Luxembourgish Proverb"),
        DailyQuote(month: 11, day: 1, en: "In every walk with nature one receives far more than he seeks.", author: "John Muir"),
        DailyQuote(month: 11, day: 2, en: "Every great dream begins with a dreamer.", author: "Harriet Tubman"),
        DailyQuote(month: 11, day: 3, en: "I may be compelled to face danger, but never fear it.", author: "Clara Barton"),
        DailyQuote(month: 11, day: 4, en: "Facts are stubborn things.", author: "John Adams"),
        DailyQuote(month: 11, day: 5, en: "Action may not always bring happiness, but there is no happiness without action.", author: "Benjamin Disraeli"),
        DailyQuote(month: 11, day: 6, en: "Arise, awake, and stop not until the goal is reached.", author: "Swami Vivekananda"),
        DailyQuote(month: 11, day: 7, en: "Take only memories, leave only footprints.", author: "Native American Proverb"),
        DailyQuote(month: 11, day: 8, en: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
        DailyQuote(month: 11, day: 9, en: "I contain multitudes.", author: "Walt Whitman"),
        DailyQuote(month: 11, day: 10, en: "Far away in the sunshine are my highest aspirations.", author: "Louisa May Alcott"),
        DailyQuote(month: 11, day: 11, en: "Reflect upon your present blessings, of which every man has many; not on your past misfortunes, of which all men have some.", author: "Charles Dickens"),
        DailyQuote(month: 11, day: 12, en: "It isn't what we say or think that defines us, but what we do.", author: "Jane Austen"),
        DailyQuote(month: 11, day: 13, en: "Laughter is the sun that drives winter from the human face.", author: "Victor Hugo"),
        DailyQuote(month: 11, day: 14, en: "If you want to be happy, be.", author: "Leo Tolstoy"),
        DailyQuote(month: 11, day: 15, en: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason.", author: "Immanuel Kant"),
        DailyQuote(month: 11, day: 16, en: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe"),
        DailyQuote(month: 11, day: 17, en: "Impossible is a word to be found only in the dictionary of fools.", author: "Napoleon Bonaparte"),
        DailyQuote(month: 11, day: 18, en: "Live your life while you have it. Life is a splendid gift.", author: "Florence Nightingale"),
        DailyQuote(month: 11, day: 19, en: "Energy rightly applied and directed can accomplish anything.", author: "Susan B. Anthony"),
        DailyQuote(month: 11, day: 20, en: "One generation plants the trees; another gets the shade.", author: "Chinese Proverb"),
        DailyQuote(month: 11, day: 21, en: "The bamboo that bends is stronger than the oak that resists.", author: "Japanese Proverb"),
        DailyQuote(month: 11, day: 22, en: "Don't let yesterday use up too much of today.", author: "Cherokee Proverb"),
        DailyQuote(month: 11, day: 23, en: "A closed hand cannot receive.", author: "Argentine Proverb"),
        DailyQuote(month: 11, day: 24, en: "He who waits achieves.", author: "Brazilian Proverb"),
        DailyQuote(month: 11, day: 25, en: "The river does not flow back.", author: "Chilean Proverb"),
        DailyQuote(month: 11, day: 26, en: "A friend is a second self.", author: "Colombian Proverb"),
        DailyQuote(month: 11, day: 27, en: "Every day is not Christmas.", author: "Trinidadian Proverb"),
        DailyQuote(month: 11, day: 28, en: "The hasty person eats the food before it is cooked.", author: "Jordanian Proverb"),
        DailyQuote(month: 11, day: 29, en: "The camel does not see its own hump.", author: "Emirati Proverb"),
        DailyQuote(month: 11, day: 30, en: "Get advice from everyone, but act with your own mind.", author: "Hebrew Proverb"),
        DailyQuote(month: 12, day: 1, en: "Do not fear going slowly; fear only to stand still.", author: "Chinese Proverb"),
        DailyQuote(month: 12, day: 2, en: "Into each life some rain must fall.", author: "Henry Wadsworth Longfellow"),
        DailyQuote(month: 12, day: 3, en: "The one who doesn't look ahead remains behind.", author: "Costa Rican Proverb"),
        DailyQuote(month: 12, day: 4, en: "A good listener needs few words.", author: "Panamanian Proverb"),
        DailyQuote(month: 12, day: 5, en: "The crab that walks too much loses its claws.", author: "Dominican Proverb"),
        DailyQuote(month: 12, day: 6, en: "Do not leave for tomorrow what can be done today.", author: "Puerto Rican Proverb"),
        DailyQuote(month: 12, day: 7, en: "He who plants good deeds gathers joy.", author: "Saudi Proverb"),
        DailyQuote(month: 12, day: 8, en: "A single hand cannot clap.", author: "Yemeni Proverb"),
        DailyQuote(month: 12, day: 9, en: "A friend is known in time of need.", author: "Iraqi Proverb"),
        DailyQuote(month: 12, day: 10, en: "Trees planted by our ancestors give us shade; let us plant for those to come.", author: "Palestinian Proverb"),
        DailyQuote(month: 12, day: 11, en: "The lizard that jumps from a high tree says it will praise itself if no one else does.", author: "Ugandan Proverb"),
        DailyQuote(month: 12, day: 12, en: "The axe forgets, but the tree remembers.", author: "Tanzanian Proverb"),
        DailyQuote(month: 12, day: 13, en: "A grateful person receives more.", author: "Zambian Proverb"),
        DailyQuote(month: 12, day: 14, en: "If you can walk, you can dance; if you can talk, you can sing.", author: "Zimbabwean Proverb"),
        DailyQuote(month: 12, day: 15, en: "Wood already touched by fire is not hard to set alight.", author: "Congolese Proverb"),
        DailyQuote(month: 12, day: 16, en: "A single bracelet does not jingle.", author: "Cameroonian Proverb"),
        DailyQuote(month: 12, day: 17, en: "Knowledge is like a garden: if it is not cultivated, it cannot be harvested.", author: "Malian Proverb"),
        DailyQuote(month: 12, day: 18, en: "It is the tree that stands alone that fears the wind.", author: "Ivorian Proverb"),
        DailyQuote(month: 12, day: 19, en: "When the music changes, so does the dance.", author: "Ghanaian Proverb"),
        DailyQuote(month: 12, day: 20, en: "A single stick may smoke, but it will not burn.", author: "Beninese Proverb"),
        DailyQuote(month: 12, day: 21, en: "The path to the well-known place is never long.", author: "Sierra Leonean Proverb"),
        DailyQuote(month: 12, day: 22, en: "You never test the depth of a river with both feet.", author: "Liberian Proverb"),
        DailyQuote(month: 12, day: 23, en: "A big ship needs deep water.", author: "Singaporean Proverb"),
        DailyQuote(month: 12, day: 24, en: "The ocean is not filled by one river alone.", author: "Samoan Proverb"),
        DailyQuote(month: 12, day: 25, en: "Every canoe needs many paddlers.", author: "Tongan Proverb"),
        DailyQuote(month: 12, day: 26, en: "A single wave does not make the ocean.", author: "Fijian Proverb"),
        DailyQuote(month: 12, day: 27, en: "Even a small path, if walked daily, becomes a road.", author: "Kyrgyz Proverb"),
        DailyQuote(month: 12, day: 28, en: "A guest for one day sees more than the host in a year.", author: "Tajik Proverb"),
        DailyQuote(month: 12, day: 29, en: "The one who learns a new language gains a new soul.", author: "Turkmen Proverb"),
        DailyQuote(month: 12, day: 30, en: "A single coconut can start a whole grove.", author: "Maldivian Proverb"),
        DailyQuote(month: 12, day: 31, en: "You may delay, but time will not.", author: "Benjamin Franklin"),
    ]

    static func quote(for date: Date = Date()) -> DailyQuote {
        let cal = Calendar.current
        let month = cal.component(.month, from: date)
        let day = cal.component(.day, from: date)
        if let exact = quotes.first(where: { $0.month == month && $0.day == day }) {
            return exact
        }
        if month == 2 && day == 29, let leapFallback = quotes.first(where: { $0.month == 2 && $0.day == 28 }) {
            return leapFallback
        }
        return quotes.first!
    }
}
