import Foundation

// GENERATED from ../../src/data/quotes.ts by scripts/sync-widget-quotes.mjs —
// do not edit by hand, run that script again after changing the dataset.
// The widget process can't import JS, so today's quote is computed
// independently here from the same month/day mapping.

struct DailyQuote {
    let month: Int
    let day: Int
    let en: String
    let author: String
}

enum QuoteStore {
    static let quotes: [DailyQuote] = [
        DailyQuote(month: 1, day: 1, en: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Proverb"),
        DailyQuote(month: 1, day: 2, en: "Well begun is half done.", author: "Aristotle"),
        DailyQuote(month: 1, day: 3, en: "Fall seven times, stand up eight.", author: "Japanese Proverb"),
        DailyQuote(month: 1, day: 4, en: "Whether you think you can, or you think you can't, you're right.", author: "Proverb"),
        DailyQuote(month: 1, day: 5, en: "A leopard cannot change its spots.", author: "English Proverb"),
        DailyQuote(month: 1, day: 6, en: "A journey of a thousand miles begins with a single step.", author: "Laozi"),
        DailyQuote(month: 1, day: 7, en: "Rome wasn't built in a day.", author: "English Proverb"),
        DailyQuote(month: 1, day: 8, en: "Forewarned is forearmed.", author: "English Proverb"),
        DailyQuote(month: 1, day: 9, en: "Little strokes fell great oaks.", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 10, en: "No pain, no gain.", author: "English Proverb"),
        DailyQuote(month: 1, day: 11, en: "Knowledge is power.", author: "Francis Bacon"),
        DailyQuote(month: 1, day: 12, en: "The unexamined life is not worth living.", author: "Socrates"),
        DailyQuote(month: 1, day: 13, en: "After a storm comes a calm.", author: "English Proverb"),
        DailyQuote(month: 1, day: 14, en: "Little by little, a little becomes a lot.", author: "Proverb"),
        DailyQuote(month: 1, day: 15, en: "Well done is better than well said.", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 16, en: "The palest ink is better than the best memory.", author: "Proverb"),
        DailyQuote(month: 1, day: 17, en: "A smooth sea never made a skilled sailor.", author: "English Proverb"),
        DailyQuote(month: 1, day: 18, en: "Diligence is the mother of good luck.", author: "Proverb"),
        DailyQuote(month: 1, day: 19, en: "Tomorrow belongs to those who prepare for it today.", author: "Proverb"),
        DailyQuote(month: 1, day: 20, en: "He who hesitates is lost.", author: "English Proverb"),
        DailyQuote(month: 1, day: 21, en: "Constant dripping wears away the stone.", author: "Latin Proverb"),
        DailyQuote(month: 1, day: 22, en: "Where there is a will, there is a way.", author: "English Proverb"),
        DailyQuote(month: 1, day: 23, en: "Practice makes perfect.", author: "English Proverb"),
        DailyQuote(month: 1, day: 24, en: "It is only the first step that is difficult.", author: "French Proverb"),
        DailyQuote(month: 1, day: 25, en: "Better late than never.", author: "English Proverb"),
        DailyQuote(month: 1, day: 26, en: "A little learning is a dangerous thing.", author: "Alexander Pope"),
        DailyQuote(month: 1, day: 27, en: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison"),
        DailyQuote(month: 1, day: 28, en: "Many hands make light work.", author: "English Proverb"),
        DailyQuote(month: 1, day: 29, en: "He that can have patience can have what he will.", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 30, en: "Nothing is impossible to a willing heart.", author: "English Proverb"),
        DailyQuote(month: 1, day: 31, en: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Oliver Goldsmith"),
        DailyQuote(month: 2, day: 1, en: "A room without books is like a body without a soul.", author: "John Lubbock"),
        DailyQuote(month: 2, day: 2, en: "Learning is a treasure that will follow its owner everywhere.", author: "Proverb"),
        DailyQuote(month: 2, day: 3, en: "A kind word is like a spring day.", author: "Russian Proverb"),
        DailyQuote(month: 2, day: 4, en: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop"),
        DailyQuote(month: 2, day: 5, en: "A friend in need is a friend indeed.", author: "English Proverb"),
        DailyQuote(month: 2, day: 6, en: "Two heads are better than one.", author: "Proverb"),
        DailyQuote(month: 2, day: 7, en: "A candle loses nothing by lighting another candle.", author: "Proverb"),
        DailyQuote(month: 2, day: 8, en: "Iron sharpens iron.", author: "Proverb"),
        DailyQuote(month: 2, day: 9, en: "Charity begins at home.", author: "English Proverb"),
        DailyQuote(month: 2, day: 10, en: "Shared joy is a double joy; shared sorrow is half a sorrow.", author: "Proverb"),
        DailyQuote(month: 2, day: 11, en: "A single arrow is easily broken, but not ten in a bundle.", author: "Japanese Proverb"),
        DailyQuote(month: 2, day: 12, en: "United we stand, divided we fall.", author: "Proverb"),
        DailyQuote(month: 2, day: 13, en: "Honesty is the best policy.", author: "English Proverb"),
        DailyQuote(month: 2, day: 14, en: "Love truth, but pardon error.", author: "Voltaire"),
        DailyQuote(month: 2, day: 15, en: "A good friend is a connection to life.", author: "Proverb"),
        DailyQuote(month: 2, day: 16, en: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson"),
        DailyQuote(month: 2, day: 17, en: "Walk beside me and be my friend.", author: "Proverb"),
        DailyQuote(month: 2, day: 18, en: "It is not the length of life, but the depth of life.", author: "Ralph Waldo Emerson"),
        DailyQuote(month: 2, day: 19, en: "Curiosity is the compass of the mind.", author: "Proverb"),
        DailyQuote(month: 2, day: 20, en: "He who asks a question is a fool for five minutes; he who does not ask remains a fool forever.", author: "Proverb"),
        DailyQuote(month: 2, day: 21, en: "Where there is unity, there is strength.", author: "English Proverb"),
        DailyQuote(month: 2, day: 22, en: "It is never too late to learn.", author: "English Proverb"),
        DailyQuote(month: 2, day: 23, en: "The more you learn, the more you realize how much you don't know.", author: "Proverb"),
        DailyQuote(month: 2, day: 24, en: "To teach is to learn twice.", author: "Joseph Joubert"),
        DailyQuote(month: 2, day: 25, en: "A good name is better than riches.", author: "English Proverb"),
        DailyQuote(month: 2, day: 26, en: "Every day is a chance to become better.", author: "Proverb"),
        DailyQuote(month: 2, day: 27, en: "Philosophy begins in wonder.", author: "Socrates"),
        DailyQuote(month: 2, day: 28, en: "He who knows others is wise; he who knows himself is enlightened.", author: "Laozi"),
        DailyQuote(month: 3, day: 1, en: "He who has a why to live can bear with almost any how.", author: "Nietzsche"),
        DailyQuote(month: 3, day: 2, en: "He conquers who endures.", author: "Persius"),
        DailyQuote(month: 3, day: 3, en: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius（意訳）"),
        DailyQuote(month: 3, day: 4, en: "Patience is the key to relief.", author: "Arabic Proverb"),
        DailyQuote(month: 3, day: 5, en: "Better safe than sorry.", author: "English Proverb"),
        DailyQuote(month: 3, day: 6, en: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus（意訳）"),
        DailyQuote(month: 3, day: 7, en: "A good laugh and a long sleep are the best cures.", author: "Proverb"),
        DailyQuote(month: 3, day: 8, en: "There is no royal road to learning.", author: "English Proverb"),
        DailyQuote(month: 3, day: 9, en: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau（意訳）"),
        DailyQuote(month: 3, day: 10, en: "Habits are first cobwebs, then cables.", author: "Spanish Proverb"),
        DailyQuote(month: 3, day: 11, en: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Proverb"),
        DailyQuote(month: 3, day: 12, en: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott"),
        DailyQuote(month: 3, day: 13, en: "No one is useless in this world who lightens the burdens of another.", author: "Charles Dickens"),
        DailyQuote(month: 3, day: 14, en: "There is nothing I would not do for those who are really my friends.", author: "Jane Austen"),
        DailyQuote(month: 3, day: 15, en: "The darkest hour is just before the dawn.", author: "English Proverb"),
        DailyQuote(month: 3, day: 16, en: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy"),
        DailyQuote(month: 3, day: 17, en: "To go wrong in one's own way is better than to go right in someone else's.", author: "Fyodor Dostoevsky"),
        DailyQuote(month: 3, day: 18, en: "All that glitters is not gold.", author: "English Proverb"),
        DailyQuote(month: 3, day: 19, en: "Great oaks from little acorns grow.", author: "English Proverb"),
        DailyQuote(month: 3, day: 20, en: "Victory belongs to the most persevering.", author: "Napoleon Bonaparte"),
        DailyQuote(month: 3, day: 21, en: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale"),
        DailyQuote(month: 3, day: 22, en: "Failure is impossible.", author: "Susan B. Anthony"),
        DailyQuote(month: 3, day: 23, en: "If there is no struggle, there is no progress.", author: "Frederick Douglass"),
        DailyQuote(month: 3, day: 24, en: "Success is measured not so much by the position one has reached, but by the obstacles overcome.", author: "Booker T. Washington"),
        DailyQuote(month: 3, day: 25, en: "Beauty is in the eye of the beholder.", author: "English Proverb"),
        DailyQuote(month: 3, day: 26, en: "The tree that does not bend with the wind will be broken by it.", author: "German Proverb"),
        DailyQuote(month: 3, day: 27, en: "Better a good friend than a bad relative.", author: "Proverb"),
        DailyQuote(month: 3, day: 28, en: "One kind word can warm three winter months.", author: "Proverb"),
        DailyQuote(month: 3, day: 29, en: "No matter how far you have gone on a wrong road, turn back.", author: "Proverb"),
        DailyQuote(month: 3, day: 30, en: "Better bend than break.", author: "Proverb"),
        DailyQuote(month: 3, day: 31, en: "There is no failure except in no longer trying.", author: "Elbert Hubbard"),
        DailyQuote(month: 4, day: 1, en: "The beginning is the most important part of the work.", author: "Plato"),
        DailyQuote(month: 4, day: 2, en: "A bird in the hand is worth two in the bush.", author: "English Proverb"),
        DailyQuote(month: 4, day: 3, en: "This above all: to thine own self be true.", author: "William Shakespeare"),
        DailyQuote(month: 4, day: 4, en: "It is better to offer no excuse than a bad one.", author: "George Washington"),
        DailyQuote(month: 4, day: 5, en: "God helps those who help themselves.", author: "English Proverb"),
        DailyQuote(month: 4, day: 6, en: "Waste not, want not.", author: "English Proverb"),
        DailyQuote(month: 4, day: 7, en: "A rolling stone gathers no moss.", author: "English Proverb"),
        DailyQuote(month: 4, day: 8, en: "If I have seen further, it is by standing on the shoulders of giants.", author: "Isaac Newton"),
        DailyQuote(month: 4, day: 9, en: "Look before you leap.", author: "English Proverb"),
        DailyQuote(month: 4, day: 10, en: "In life, there is nothing to be feared, only understood.", author: "Marie Curie"),
        DailyQuote(month: 4, day: 11, en: "What comes from the heart, enters the heart.", author: "Proverb"),
        DailyQuote(month: 4, day: 12, en: "Ask the experienced rather than the learned.", author: "Proverb"),
        DailyQuote(month: 4, day: 13, en: "A good beginning makes a good ending.", author: "Proverb"),
        DailyQuote(month: 4, day: 14, en: "He who does not advance, goes backward.", author: "Proverb"),
        DailyQuote(month: 4, day: 15, en: "After the game, the king and the pawn go into the same box.", author: "Italian Proverb"),
        DailyQuote(month: 4, day: 16, en: "One who wants a rose must respect the thorn.", author: "Proverb"),
        DailyQuote(month: 4, day: 17, en: "A drop of patience is worth more than a bushel of brains.", author: "Proverb"),
        DailyQuote(month: 4, day: 18, en: "Do good and cast it into the sea.", author: "Proverb"),
        DailyQuote(month: 4, day: 19, en: "Going through hardship is going through a school.", author: "Proverb"),
        DailyQuote(month: 4, day: 20, en: "A gem cannot be polished without friction, nor a person perfected without trials.", author: "Proverb"),
        DailyQuote(month: 4, day: 21, en: "He who does not look back at where he came from will not reach his destination.", author: "Proverb"),
        DailyQuote(month: 4, day: 22, en: "He who chases two hares catches neither.", author: "Proverb"),
        DailyQuote(month: 4, day: 23, en: "Happiness is a place between too little and too much.", author: "Proverb"),
        DailyQuote(month: 4, day: 24, en: "There is no such thing as bad weather, only bad clothes.", author: "Proverb"),
        DailyQuote(month: 4, day: 25, en: "A book is a mute teacher.", author: "Proverb"),
        DailyQuote(month: 4, day: 26, en: "Waste no more time arguing about what a good person should be. Be one.", author: "Marcus Aurelius"),
        DailyQuote(month: 4, day: 27, en: "The pen is mightier than the sword.", author: "English Proverb"),
        DailyQuote(month: 4, day: 28, en: "First say to yourself what you would be, and then do what you have to do.", author: "Epictetus"),
        DailyQuote(month: 4, day: 29, en: "So long as there is life in the sick man, it is said that there is hope.", author: "Cicero"),
        DailyQuote(month: 4, day: 30, en: "Actions speak louder than words.", author: "English Proverb"),
        DailyQuote(month: 5, day: 1, en: "When the going gets tough, the tough get going.", author: "English Proverb"),
        DailyQuote(month: 5, day: 2, en: "You reap what you sow.", author: "English Proverb"),
        DailyQuote(month: 5, day: 3, en: "Every dog has its day.", author: "English Proverb"),
        DailyQuote(month: 5, day: 4, en: "Birds of a feather flock together.", author: "English Proverb"),
        DailyQuote(month: 5, day: 5, en: "Wisdom outweighs any wealth.", author: "Sophocles"),
        DailyQuote(month: 5, day: 6, en: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch"),
        DailyQuote(month: 5, day: 7, en: "Nothing is stronger than habit.", author: "Ovid"),
        DailyQuote(month: 5, day: 8, en: "Seize the day, trusting little in tomorrow.", author: "Horace"),
        DailyQuote(month: 5, day: 9, en: "There's no place like home.", author: "English Proverb"),
        DailyQuote(month: 5, day: 10, en: "The great man is he who does not lose his child's heart.", author: "Mencius"),
        DailyQuote(month: 5, day: 11, en: "Curiosity killed the cat.", author: "English Proverb"),
        DailyQuote(month: 5, day: 12, en: "Today is victory over yourself of yesterday.", author: "Miyamoto Musashi"),
        DailyQuote(month: 5, day: 13, en: "If you want your dreams to come true, don't sleep.", author: "Proverb"),
        DailyQuote(month: 5, day: 14, en: "When spider webs unite, they can tie up a lion.", author: "Proverb"),
        DailyQuote(month: 5, day: 15, en: "However long the night, the dawn will break.", author: "Proverb"),
        DailyQuote(month: 5, day: 16, en: "What is the most important thing in the world? It is people, it is people, it is people.", author: "Proverb"),
        DailyQuote(month: 5, day: 17, en: "Not all knowledge is found in one place.", author: "Proverb"),
        DailyQuote(month: 5, day: 18, en: "Tell me and I forget, teach me and I remember, involve me and I learn.", author: "Proverb"),
        DailyQuote(month: 5, day: 19, en: "Repetition is the mother of learning.", author: "Russian Proverb"),
        DailyQuote(month: 5, day: 20, en: "Old men plant trees whose shade they will never sit in.", author: "Proverb"),
        DailyQuote(month: 5, day: 21, en: "The wise man keeps his tongue in his heart.", author: "Proverb"),
        DailyQuote(month: 5, day: 22, en: "A book is like a garden carried in the pocket.", author: "Proverb"),
        DailyQuote(month: 5, day: 23, en: "A single spark can start a great fire.", author: "Proverb"),
        DailyQuote(month: 5, day: 24, en: "Do not fix your eyes on the road behind others; look at your own road.", author: "Proverb"),
        DailyQuote(month: 5, day: 25, en: "Because of a mistake, you learn something you did not know before.", author: "Proverb"),
        DailyQuote(month: 5, day: 26, en: "Light burdens become heavy if carried far.", author: "Proverb"),
        DailyQuote(month: 5, day: 27, en: "It is best to do things in the right order.", author: "Proverb"),
        DailyQuote(month: 5, day: 28, en: "He who wants to eat the kernel must crack the nut.", author: "Proverb"),
        DailyQuote(month: 5, day: 29, en: "Practice makes the master.", author: "Proverb"),
        DailyQuote(month: 5, day: 30, en: "Work praises the master.", author: "Proverb"),
        DailyQuote(month: 5, day: 31, en: "A guest is a gift, whether they come early or late.", author: "Proverb"),
        DailyQuote(month: 6, day: 1, en: "The heart has its reasons which reason does not know.", author: "Blaise Pascal"),
        DailyQuote(month: 6, day: 2, en: "It is not enough to have a good mind; the main thing is to use it well.", author: "René Descartes"),
        DailyQuote(month: 6, day: 3, en: "It is sometimes said that common sense is very rare.", author: "Voltaire"),
        DailyQuote(month: 6, day: 4, en: "Two wrongs don't make a right.", author: "English Proverb"),
        DailyQuote(month: 6, day: 5, en: "Come forth into the light of things, let Nature be your teacher.", author: "William Wordsworth"),
        DailyQuote(month: 6, day: 6, en: "A thing of beauty is a joy forever.", author: "John Keats"),
        DailyQuote(month: 6, day: 7, en: "If winter comes, can spring be far behind?", author: "Percy Bysshe Shelley"),
        DailyQuote(month: 6, day: 8, en: "To strive, to seek, to find, and not to yield.", author: "Alfred Lord Tennyson"),
        DailyQuote(month: 6, day: 9, en: "The grass is always greener on the other side.", author: "English Proverb"),
        DailyQuote(month: 6, day: 10, en: "Out of sight, out of mind.", author: "English Proverb"),
        DailyQuote(month: 6, day: 11, en: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson"),
        DailyQuote(month: 6, day: 12, en: "All good things must come to an end.", author: "English Proverb"),
        DailyQuote(month: 6, day: 13, en: "Don't put all your eggs in one basket.", author: "English Proverb"),
        DailyQuote(month: 6, day: 14, en: "Better to fail in originality than to succeed in imitation.", author: "Herman Melville"),
        DailyQuote(month: 6, day: 15, en: "I am no bird; and no net ensnares me; I am a free human being with an independent will.", author: "Charlotte Brontë"),
        DailyQuote(month: 6, day: 16, en: "Progress is the law of life.", author: "Robert Browning"),
        DailyQuote(month: 6, day: 17, en: "Absence makes the heart grow fonder.", author: "English Proverb"),
        DailyQuote(month: 6, day: 18, en: "No man's knowledge here can go beyond his experience.", author: "John Locke"),
        DailyQuote(month: 6, day: 19, en: "Nature never deceives us; it is we who deceive ourselves.", author: "Jean-Jacques Rousseau"),
        DailyQuote(month: 6, day: 20, en: "Success in the majority of circumstances depends on knowing how long it takes to succeed.", author: "Montesquieu"),
        DailyQuote(month: 6, day: 21, en: "A book holds a house of gold.", author: "Chinese Proverb"),
        DailyQuote(month: 6, day: 22, en: "To know everything is to know nothing.", author: "French Proverb"),
        DailyQuote(month: 6, day: 23, en: "Listen or your tongue will make you deaf.", author: "Proverb"),
        DailyQuote(month: 6, day: 24, en: "Fortune favors the bold.", author: "Latin Proverb"),
        DailyQuote(month: 6, day: 25, en: "Speak little, do much.", author: "Spanish Proverb"),
        DailyQuote(month: 6, day: 26, en: "The morning hour has gold in its mouth.", author: "German Proverb"),
        DailyQuote(month: 6, day: 27, en: "The clever man is not the one who gets out of a difficulty easily, but who does not get into it.", author: "Arabic Proverb"),
        DailyQuote(month: 6, day: 28, en: "It takes a village to raise a child.", author: "African Proverb"),
        DailyQuote(month: 6, day: 29, en: "Slow and steady wins the race.", author: "Aesop"),
        DailyQuote(month: 6, day: 30, en: "Practice what you preach.", author: "English Proverb"),
        DailyQuote(month: 7, day: 1, en: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton"),
        DailyQuote(month: 7, day: 2, en: "The early bird catches the worm.", author: "English Proverb"),
        DailyQuote(month: 7, day: 3, en: "All that we see or seem is but a dream within a dream.", author: "Edgar Allan Poe"),
        DailyQuote(month: 7, day: 4, en: "Great things are done when men and mountains meet.", author: "William Blake"),
        DailyQuote(month: 7, day: 5, en: "The best-laid schemes of mice and men often go awry.", author: "Robert Burns"),
        DailyQuote(month: 7, day: 6, en: "Vision is the art of seeing what is invisible to others.", author: "Jonathan Swift"),
        DailyQuote(month: 7, day: 7, en: "Fear of danger is ten thousand times more terrifying than danger itself.", author: "Daniel Defoe"),
        DailyQuote(month: 7, day: 8, en: "Advice is like snow; the softer it falls, the longer it dwells upon the mind.", author: "Samuel Taylor Coleridge"),
        DailyQuote(month: 7, day: 9, en: "If we had no winter, the spring would not be so pleasant.", author: "Anne Bradstreet"),
        DailyQuote(month: 7, day: 10, en: "He that is down needs fear no fall.", author: "John Bunyan"),
        DailyQuote(month: 7, day: 11, en: "Unity is strength, division is weakness.", author: "Proverb"),
        DailyQuote(month: 7, day: 12, en: "However far the stream flows, it never forgets its source.", author: "Proverb"),
        DailyQuote(month: 7, day: 13, en: "A person is a person through other persons.", author: "Zulu Proverb"),
        DailyQuote(month: 7, day: 14, en: "No one shows a child the sky.", author: "Proverb"),
        DailyQuote(month: 7, day: 15, en: "Rain does not fall on one roof alone.", author: "Proverb"),
        DailyQuote(month: 7, day: 16, en: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Proverb"),
        DailyQuote(month: 7, day: 17, en: "Do not compare your chapter one with someone else's chapter twenty.", author: "Proverb"),
        DailyQuote(month: 7, day: 18, en: "Do not throw away the ladder after you have climbed the wall.", author: "Proverb"),
        DailyQuote(month: 7, day: 19, en: "A tree is known by its fruit.", author: "Proverb"),
        DailyQuote(month: 7, day: 20, en: "He who seeks, finds.", author: "Proverb"),
        DailyQuote(month: 7, day: 21, en: "Ask a wise question, get a wise answer.", author: "Proverb"),
        DailyQuote(month: 7, day: 22, en: "A friend's eye is a good mirror.", author: "Proverb"),
        DailyQuote(month: 7, day: 23, en: "Even a small bee can sting a big bear.", author: "Proverb"),
        DailyQuote(month: 7, day: 24, en: "Knowledge without practice is a tree without fruit.", author: "Proverb"),
        DailyQuote(month: 7, day: 25, en: "A single tree does not make a forest.", author: "Proverb"),
        DailyQuote(month: 7, day: 26, en: "Be humble, for you are made of earth. Be noble, for you are made of stars.", author: "Proverb"),
        DailyQuote(month: 7, day: 27, en: "Little children step on your toes; big children step on your heart.", author: "Proverb"),
        DailyQuote(month: 7, day: 28, en: "The apple doesn't fall far from the tree.", author: "Proverb"),
        DailyQuote(month: 7, day: 29, en: "Together we are strong; apart we are weak.", author: "Proverb"),
        DailyQuote(month: 7, day: 30, en: "Every path has its puddle.", author: "Proverb"),
        DailyQuote(month: 7, day: 31, en: "A good word is like a spring rain.", author: "Proverb"),
        DailyQuote(month: 8, day: 1, en: "Chance favors the prepared mind.", author: "Louis Pasteur"),
        DailyQuote(month: 8, day: 2, en: "Don't wait for inspiration; go after it with a club.", author: "Jack London"),
        DailyQuote(month: 8, day: 3, en: "Great is the art of beginning, but greater is the art of ending.", author: "Henry Wadsworth Longfellow"),
        DailyQuote(month: 8, day: 4, en: "Not failure, but low aim, is crime.", author: "James Russell Lowell"),
        DailyQuote(month: 8, day: 5, en: "Little by little does the trick.", author: "English Proverb"),
        DailyQuote(month: 8, day: 6, en: "Don't count your chickens before they hatch.", author: "English Proverb"),
        DailyQuote(month: 8, day: 7, en: "A man who does not think for himself does not think at all.", author: "English Proverb"),
        DailyQuote(month: 8, day: 8, en: "Every wall is a door.", author: "Proverb"),
        DailyQuote(month: 8, day: 9, en: "Have something to say, and say it as clearly as you can.", author: "Matthew Arnold"),
        DailyQuote(month: 8, day: 10, en: "What we learn with pleasure we never forget.", author: "English Proverb"),
        DailyQuote(month: 8, day: 11, en: "The squeaky wheel gets the grease.", author: "English Proverb"),
        DailyQuote(month: 8, day: 12, en: "Aim for the moon. If you miss, you may hit a star.", author: "English Proverb"),
        DailyQuote(month: 8, day: 13, en: "Be ashamed to die until you have won some victory for humanity.", author: "Horace Mann"),
        DailyQuote(month: 8, day: 14, en: "Beyond the mountains, more mountains.", author: "Haitian Proverb"),
        DailyQuote(month: 8, day: 15, en: "Time longer than rope.", author: "Proverb"),
        DailyQuote(month: 8, day: 16, en: "The shrimp that falls asleep is carried away by the current.", author: "Proverb"),
        DailyQuote(month: 8, day: 17, en: "The mountain does not come to you; you must go to the mountain.", author: "Proverb"),
        DailyQuote(month: 8, day: 18, en: "However tired you may be, do not lean on a rotten stick.", author: "Proverb"),
        DailyQuote(month: 8, day: 19, en: "Speech is silver, but silence is golden.", author: "English Proverb"),
        DailyQuote(month: 8, day: 20, en: "Even a small ant can build a big anthill.", author: "Proverb"),
        DailyQuote(month: 8, day: 21, en: "Knowledge grows when it is shared.", author: "Proverb"),
        DailyQuote(month: 8, day: 22, en: "It is easier to know how to speak than to know when to be silent.", author: "Proverb"),
        DailyQuote(month: 8, day: 23, en: "The buffalo that arrives first drinks the clean water.", author: "Proverb"),
        DailyQuote(month: 8, day: 24, en: "The elephant's tusks cannot be hidden in its mouth.", author: "Proverb"),
        DailyQuote(month: 8, day: 25, en: "Whoever wants makes progress; whoever does not want, offers excuses.", author: "Proverb"),
        DailyQuote(month: 8, day: 26, en: "Only those who do nothing make no mistakes.", author: "Proverb"),
        DailyQuote(month: 8, day: 27, en: "Everyone is the smith of their own fortune.", author: "Proverb"),
        DailyQuote(month: 8, day: 28, en: "Small deeds done are better than great deeds planned.", author: "Proverb"),
        DailyQuote(month: 8, day: 29, en: "He who wants to eat honey must brave the bee sting.", author: "Proverb"),
        DailyQuote(month: 8, day: 30, en: "A kind word is worth more than a rich gift.", author: "Proverb"),
        DailyQuote(month: 8, day: 31, en: "Every cloud has a silver lining.", author: "English Proverb"),
        DailyQuote(month: 9, day: 1, en: "He who conquers himself is the mightiest warrior.", author: "Proverb"),
        DailyQuote(month: 9, day: 2, en: "Penny wise, pound foolish.", author: "English Proverb"),
        DailyQuote(month: 9, day: 3, en: "Not till we are lost do we begin to find ourselves.", author: "Henry David Thoreau"),
        DailyQuote(month: 9, day: 4, en: "What lies behind us and what lies before us are small matters compared to what lies within us.", author: "Proverb"),
        DailyQuote(month: 9, day: 5, en: "Few things help an individual more than to place responsibility upon him, and to let him know that you trust him.", author: "Booker T. Washington"),
        DailyQuote(month: 9, day: 6, en: "Power concedes nothing without a demand. It never did and it never will.", author: "Frederick Douglass"),
        DailyQuote(month: 9, day: 7, en: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt"),
        DailyQuote(month: 9, day: 8, en: "Simplicity is the ultimate sophistication.", author: "Proverb"),
        DailyQuote(month: 9, day: 9, en: "Nothing ventured, nothing gained.", author: "English Proverb"),
        DailyQuote(month: 9, day: 10, en: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius"),
        DailyQuote(month: 9, day: 11, en: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca"),
        DailyQuote(month: 9, day: 12, en: "No man is free who is not master of himself.", author: "Proverb"),
        DailyQuote(month: 9, day: 13, en: "To be ignorant of what happened before you were born is to be forever a child.", author: "Cicero"),
        DailyQuote(month: 9, day: 14, en: "Know thyself.", author: "Delphic Maxim"),
        DailyQuote(month: 9, day: 15, en: "A stitch in time saves nine.", author: "English Proverb"),
        DailyQuote(month: 9, day: 16, en: "To thine own self be true.", author: "William Shakespeare"),
        DailyQuote(month: 9, day: 17, en: "Necessity is the mother of invention.", author: "English Proverb"),
        DailyQuote(month: 9, day: 18, en: "We know what we are, but know not what we may be.", author: "William Shakespeare"),
        DailyQuote(month: 9, day: 19, en: "Judge a man by his questions rather than his answers.", author: "Duc de Lévis"),
        DailyQuote(month: 9, day: 20, en: "You can lead a horse to water, but you can't make it drink.", author: "English Proverb"),
        DailyQuote(month: 9, day: 21, en: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Proverb"),
        DailyQuote(month: 9, day: 22, en: "You can't judge a book by its cover.", author: "English Proverb"),
        DailyQuote(month: 9, day: 23, en: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb"),
        DailyQuote(month: 9, day: 24, en: "A wise man does not need advice, and a fool doesn't take it.", author: "Arabic Proverb"),
        DailyQuote(month: 9, day: 25, en: "Through hardships to the stars.", author: "Latin Proverb"),
        DailyQuote(month: 9, day: 26, en: "Little by little, the camel enters the couscous.", author: "Proverb"),
        DailyQuote(month: 9, day: 27, en: "A stumble may prevent a fall.", author: "Proverb"),
        DailyQuote(month: 9, day: 28, en: "The dogs bark, but the caravan moves on.", author: "Proverb"),
        DailyQuote(month: 9, day: 29, en: "The one who does not travel thinks their mother is the best cook.", author: "Proverb"),
        DailyQuote(month: 9, day: 30, en: "The person who wakes up first, sees more of the day.", author: "Proverb"),
        DailyQuote(month: 10, day: 1, en: "You cannot make an omelette without breaking eggs.", author: "English Proverb"),
        DailyQuote(month: 10, day: 2, en: "Nothing can stop the man with the right mental attitude from achieving his goal.", author: "Proverb"),
        DailyQuote(month: 10, day: 3, en: "A house divided against itself cannot stand.", author: "Abraham Lincoln"),
        DailyQuote(month: 10, day: 4, en: "Actions, not words, are the true criterion of attachment.", author: "George Washington"),
        DailyQuote(month: 10, day: 5, en: "Better three hours too soon than a minute too late.", author: "William Shakespeare"),
        DailyQuote(month: 10, day: 6, en: "The greater danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.", author: "Proverb"),
        DailyQuote(month: 10, day: 7, en: "One never notices what has been done; one can only see what remains to be done.", author: "Marie Curie"),
        DailyQuote(month: 10, day: 8, en: "Appearances are often deceiving.", author: "Aesop"),
        DailyQuote(month: 10, day: 9, en: "A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success.", author: "Elbert Hubbard"),
        DailyQuote(month: 10, day: 10, en: "To play a wrong note is insignificant; to play without passion is inexcusable.", author: "Proverb"),
        DailyQuote(month: 10, day: 11, en: "Nothing is too wonderful to be true.", author: "Michael Faraday"),
        DailyQuote(month: 10, day: 12, en: "A penny saved is a penny earned.", author: "English Proverb"),
        DailyQuote(month: 10, day: 13, en: "I am seeking, I am striving, I am in it with all my heart.", author: "Vincent van Gogh"),
        DailyQuote(month: 10, day: 14, en: "Children have more need of models than of critics.", author: "Joseph Joubert"),
        DailyQuote(month: 10, day: 15, en: "To err is human, to forgive divine.", author: "Alexander Pope"),
        DailyQuote(month: 10, day: 16, en: "Reading maketh a full man, conference a ready man, and writing an exact man.", author: "Francis Bacon"),
        DailyQuote(month: 10, day: 17, en: "Divide each difficulty into as many parts as is feasible.", author: "René Descartes"),
        DailyQuote(month: 10, day: 18, en: "A closed mouth catches no flies.", author: "Chinese Proverb"),
        DailyQuote(month: 10, day: 19, en: "The reputation of a thousand years may be determined by the conduct of one hour.", author: "Proverb"),
        DailyQuote(month: 10, day: 20, en: "Even monkeys fall from trees.", author: "Proverb"),
        DailyQuote(month: 10, day: 21, en: "When eating fruit, remember who planted the tree.", author: "Proverb"),
        DailyQuote(month: 10, day: 22, en: "The one who plants a tree, plants hope.", author: "Proverb"),
        DailyQuote(month: 10, day: 23, en: "Happiness is a direction, not a destination.", author: "Proverb"),
        DailyQuote(month: 10, day: 24, en: "Better a diamond with a flaw than a pebble without one.", author: "Proverb"),
        DailyQuote(month: 10, day: 25, en: "He who does not know how to smile should not open a shop.", author: "Proverb"),
        DailyQuote(month: 10, day: 26, en: "The wolf changes his coat, but not his character.", author: "Proverb"),
        DailyQuote(month: 10, day: 27, en: "A good neighbor is better than a distant friend.", author: "Proverb"),
        DailyQuote(month: 10, day: 28, en: "Little said, soon mended.", author: "Proverb"),
        DailyQuote(month: 10, day: 29, en: "Every beginning is hard.", author: "Proverb"),
        DailyQuote(month: 10, day: 30, en: "Small rain lays great dust.", author: "Proverb"),
        DailyQuote(month: 10, day: 31, en: "Time teaches more than a wise man.", author: "Proverb"),
        DailyQuote(month: 11, day: 1, en: "In every walk with nature one receives far more than he seeks.", author: "John Muir"),
        DailyQuote(month: 11, day: 2, en: "Every great dream begins with a dreamer.", author: "Proverb"),
        DailyQuote(month: 11, day: 3, en: "The surest way not to fail is to determine to succeed.", author: "Richard Brinsley Sheridan"),
        DailyQuote(month: 11, day: 4, en: "Facts are stubborn things.", author: "John Adams"),
        DailyQuote(month: 11, day: 5, en: "The secret of success is constancy of purpose.", author: "Benjamin Disraeli"),
        DailyQuote(month: 11, day: 6, en: "Arise, awake, and stop not until the goal is reached.", author: "Swami Vivekananda"),
        DailyQuote(month: 11, day: 7, en: "Take only memories, leave only footprints.", author: "Proverb"),
        DailyQuote(month: 11, day: 8, en: "It is curious that physical courage should be so common and moral courage so rare.", author: "Proverb"),
        DailyQuote(month: 11, day: 9, en: "I contain multitudes.", author: "Walt Whitman"),
        DailyQuote(month: 11, day: 10, en: "Far away in the sunshine are my highest aspirations.", author: "Louisa May Alcott"),
        DailyQuote(month: 11, day: 11, en: "Reflect upon your present blessings, of which every man has many; not on your past misfortunes, of which all men have some.", author: "Charles Dickens"),
        DailyQuote(month: 11, day: 12, en: "It isn't what we say or think that defines us, but what we do.", author: "Proverb"),
        DailyQuote(month: 11, day: 13, en: "Nothing is stronger than an idea whose time has come.", author: "Proverb"),
        DailyQuote(month: 11, day: 14, en: "A watched pot never boils.", author: "English Proverb"),
        DailyQuote(month: 11, day: 15, en: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason.", author: "Immanuel Kant"),
        DailyQuote(month: 11, day: 16, en: "He who moves not forward, goes backward.", author: "Johann Wolfgang von Goethe"),
        DailyQuote(month: 11, day: 17, en: "Impossible is a word to be found only in the dictionary of fools.", author: "Napoleon Bonaparte"),
        DailyQuote(month: 11, day: 18, en: "Make hay while the sun shines.", author: "English Proverb"),
        DailyQuote(month: 11, day: 19, en: "Don't cross the bridge until you come to it.", author: "English Proverb"),
        DailyQuote(month: 11, day: 20, en: "One generation plants the trees; another gets the shade.", author: "Proverb"),
        DailyQuote(month: 11, day: 21, en: "The bamboo that bends is stronger than the oak that resists.", author: "Proverb"),
        DailyQuote(month: 11, day: 22, en: "Don't let yesterday use up too much of today.", author: "Proverb"),
        DailyQuote(month: 11, day: 23, en: "A closed hand cannot receive.", author: "Proverb"),
        DailyQuote(month: 11, day: 24, en: "He who waits achieves.", author: "Proverb"),
        DailyQuote(month: 11, day: 25, en: "The river does not flow back.", author: "Proverb"),
        DailyQuote(month: 11, day: 26, en: "A friend is a second self.", author: "Proverb"),
        DailyQuote(month: 11, day: 27, en: "Every day is not Christmas.", author: "Proverb"),
        DailyQuote(month: 11, day: 28, en: "The hasty person eats the food before it is cooked.", author: "Proverb"),
        DailyQuote(month: 11, day: 29, en: "The camel does not see its own hump.", author: "Proverb"),
        DailyQuote(month: 11, day: 30, en: "Get advice from everyone, but act with your own mind.", author: "Proverb"),
        DailyQuote(month: 12, day: 1, en: "Do not fear going slowly; fear only to stand still.", author: "Proverb"),
        DailyQuote(month: 12, day: 2, en: "Into each life some rain must fall.", author: "Henry Wadsworth Longfellow"),
        DailyQuote(month: 12, day: 3, en: "The one who doesn't look ahead remains behind.", author: "Proverb"),
        DailyQuote(month: 12, day: 4, en: "A good listener needs few words.", author: "Proverb"),
        DailyQuote(month: 12, day: 5, en: "The crab that walks too much loses its claws.", author: "Proverb"),
        DailyQuote(month: 12, day: 6, en: "Do not leave for tomorrow what can be done today.", author: "Proverb"),
        DailyQuote(month: 12, day: 7, en: "He who plants good deeds gathers joy.", author: "Proverb"),
        DailyQuote(month: 12, day: 8, en: "A single hand cannot clap.", author: "Proverb"),
        DailyQuote(month: 12, day: 9, en: "A friend is known in time of need.", author: "Proverb"),
        DailyQuote(month: 12, day: 10, en: "Trees planted by our ancestors give us shade; let us plant for those to come.", author: "Proverb"),
        DailyQuote(month: 12, day: 11, en: "The lizard that jumps from a high tree says it will praise itself if no one else does.", author: "Proverb"),
        DailyQuote(month: 12, day: 12, en: "The axe forgets, but the tree remembers.", author: "Proverb"),
        DailyQuote(month: 12, day: 13, en: "A grateful person receives more.", author: "Proverb"),
        DailyQuote(month: 12, day: 14, en: "If you can walk, you can dance; if you can talk, you can sing.", author: "Proverb"),
        DailyQuote(month: 12, day: 15, en: "Wood already touched by fire is not hard to set alight.", author: "Proverb"),
        DailyQuote(month: 12, day: 16, en: "A single bracelet does not jingle.", author: "Proverb"),
        DailyQuote(month: 12, day: 17, en: "Knowledge is like a garden: if it is not cultivated, it cannot be harvested.", author: "Proverb"),
        DailyQuote(month: 12, day: 18, en: "It is the tree that stands alone that fears the wind.", author: "Proverb"),
        DailyQuote(month: 12, day: 19, en: "When the music changes, so does the dance.", author: "Proverb"),
        DailyQuote(month: 12, day: 20, en: "A single stick may smoke, but it will not burn.", author: "Proverb"),
        DailyQuote(month: 12, day: 21, en: "The path to the well-known place is never long.", author: "Proverb"),
        DailyQuote(month: 12, day: 22, en: "You never test the depth of a river with both feet.", author: "Proverb"),
        DailyQuote(month: 12, day: 23, en: "A big ship needs deep water.", author: "Proverb"),
        DailyQuote(month: 12, day: 24, en: "The ocean is not filled by one river alone.", author: "Proverb"),
        DailyQuote(month: 12, day: 25, en: "Every canoe needs many paddlers.", author: "Proverb"),
        DailyQuote(month: 12, day: 26, en: "A single wave does not make the ocean.", author: "Proverb"),
        DailyQuote(month: 12, day: 27, en: "Even a small path, if walked daily, becomes a road.", author: "Proverb"),
        DailyQuote(month: 12, day: 28, en: "A guest for one day sees more than the host in a year.", author: "Proverb"),
        DailyQuote(month: 12, day: 29, en: "The one who learns a new language gains a new soul.", author: "Proverb"),
        DailyQuote(month: 12, day: 30, en: "A single coconut can start a whole grove.", author: "Proverb"),
        DailyQuote(month: 12, day: 31, en: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin"),
    ]

    static func quote(for date: Date = Date()) -> DailyQuote {
        let cal = Calendar.current
        let month = cal.component(.month, from: date)
        let day = cal.component(.day, from: date)
        if let exact = quotes.first(where: { $0.month == month && $0.day == day }) {
            return exact
        }
        if month == 2 && day == 29, let leapFallback = quotes.first(where: { $0.month == 2 && $0.day == 28 }) {
            return leapFallback
        }
        return quotes.first!
    }
}
