import Foundation

// GENERATED from ../../src/data/quotes.ts by scripts/sync-widget-quotes.mjs —
// do not edit by hand, run that script again after changing the dataset.
// The widget process can't import JS, so today's quote is computed
// independently here from the same month/day mapping.

struct DailyQuote {
    let month: Int
    let day: Int
    let en: String
    let ja: String
    let author: String
}

enum QuoteStore {
    static let quotes: [DailyQuote] = [
        DailyQuote(month: 1, day: 1, en: "The best time to plant a tree was 20 years ago. The second best time is now.", ja: "木を植える最良の時期は20年前だった。次に良い時期は、今だ。", author: "Proverb"),
        DailyQuote(month: 1, day: 2, en: "Well begun is half done.", ja: "始めが良ければ半分終わったようなもの。", author: "Aristotle"),
        DailyQuote(month: 1, day: 3, en: "Fall seven times, stand up eight.", ja: "七転び八起き。", author: "Japanese Proverb"),
        DailyQuote(month: 1, day: 4, en: "Whether you think you can, or you think you can't, you're right.", ja: "できると思っても、できないと思っても、どちらも正しい。", author: "Proverb"),
        DailyQuote(month: 1, day: 5, en: "A leopard cannot change its spots.", ja: "ヒョウは自分の斑点を変えられない。（生まれ持った性質は変わらない）", author: "English Proverb"),
        DailyQuote(month: 1, day: 6, en: "A journey of a thousand miles begins with a single step.", ja: "千里の道も一歩から。", author: "Laozi"),
        DailyQuote(month: 1, day: 7, en: "Rome wasn't built in a day.", ja: "ローマは一日にして成らず。", author: "English Proverb"),
        DailyQuote(month: 1, day: 8, en: "Forewarned is forearmed.", ja: "前もって知っていれば、前もって備えられる。", author: "English Proverb"),
        DailyQuote(month: 1, day: 9, en: "Little strokes fell great oaks.", ja: "小さな一打ちも積み重なれば大木を倒す。", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 10, en: "No pain, no gain.", ja: "痛みなくして得るものなし。", author: "English Proverb"),
        DailyQuote(month: 1, day: 11, en: "Knowledge is power.", ja: "知識は力なり。", author: "Francis Bacon"),
        DailyQuote(month: 1, day: 12, en: "The unexamined life is not worth living.", ja: "吟味されていない人生は、生きるに値しない。", author: "Socrates"),
        DailyQuote(month: 1, day: 13, en: "After a storm comes a calm.", ja: "嵐のあとには、凪が来る。", author: "English Proverb"),
        DailyQuote(month: 1, day: 14, en: "Little by little, a little becomes a lot.", ja: "少しずつでも、積み重なれば大きくなる。", author: "Proverb"),
        DailyQuote(month: 1, day: 15, en: "Well done is better than well said.", ja: "うまく言うことより、うまくやることの方が良い。", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 16, en: "The palest ink is better than the best memory.", ja: "どんなに薄い墨でも、最高の記憶力に勝る。", author: "Proverb"),
        DailyQuote(month: 1, day: 17, en: "A smooth sea never made a skilled sailor.", ja: "穏やかな海は、熟練した船乗りを育てない。", author: "English Proverb"),
        DailyQuote(month: 1, day: 18, en: "Diligence is the mother of good luck.", ja: "勤勉は幸運の母である。", author: "Proverb"),
        DailyQuote(month: 1, day: 19, en: "Tomorrow belongs to those who prepare for it today.", ja: "明日は、今日それに備える者のものだ。", author: "Proverb"),
        DailyQuote(month: 1, day: 20, en: "He who hesitates is lost.", ja: "ためらう者は機会を失う。", author: "English Proverb"),
        DailyQuote(month: 1, day: 21, en: "Constant dripping wears away the stone.", ja: "絶え間なく落ちる水滴が、石をうがつ。", author: "Latin Proverb"),
        DailyQuote(month: 1, day: 22, en: "Where there is a will, there is a way.", ja: "意志あるところに道は開ける。", author: "English Proverb"),
        DailyQuote(month: 1, day: 23, en: "Practice makes perfect.", ja: "習うより慣れよ。", author: "English Proverb"),
        DailyQuote(month: 1, day: 24, en: "It is only the first step that is difficult.", ja: "難しいのは、最初の一歩だけだ。", author: "French Proverb"),
        DailyQuote(month: 1, day: 25, en: "Better late than never.", ja: "遅れても、やらないよりはましだ。", author: "English Proverb"),
        DailyQuote(month: 1, day: 26, en: "A little learning is a dangerous thing.", ja: "生半可な学びは、危険なものだ。", author: "Alexander Pope"),
        DailyQuote(month: 1, day: 27, en: "Genius is one percent inspiration and ninety-nine percent perspiration.", ja: "天才とは1%のひらめきと、99%の努力である。", author: "Thomas Edison"),
        DailyQuote(month: 1, day: 28, en: "Many hands make light work.", ja: "多くの手が集まれば、仕事は軽くなる。", author: "English Proverb"),
        DailyQuote(month: 1, day: 29, en: "He that can have patience can have what he will.", ja: "忍耐強い者は、望むものを手に入れられる。", author: "Benjamin Franklin"),
        DailyQuote(month: 1, day: 30, en: "Nothing is impossible to a willing heart.", ja: "意志ある心に、不可能はない。", author: "English Proverb"),
        DailyQuote(month: 1, day: 31, en: "Our greatest glory is not in never falling, but in rising every time we fall.", ja: "私たちの最大の栄光は、決して転ばないことではなく、転ぶたびに起き上がることにある。", author: "Oliver Goldsmith"),
        DailyQuote(month: 2, day: 1, en: "A room without books is like a body without a soul.", ja: "本のない部屋は、魂のない体のようなものだ。", author: "John Lubbock"),
        DailyQuote(month: 2, day: 2, en: "Learning is a treasure that will follow its owner everywhere.", ja: "学びは、持ち主にどこまでもついてくる宝物だ。", author: "Proverb"),
        DailyQuote(month: 2, day: 3, en: "A kind word is like a spring day.", ja: "親切な言葉は、春の日のようなものだ。", author: "Russian Proverb"),
        DailyQuote(month: 2, day: 4, en: "No act of kindness, no matter how small, is ever wasted.", ja: "どんなに小さな親切な行為も、決して無駄にはならない。", author: "Aesop"),
        DailyQuote(month: 2, day: 5, en: "A friend in need is a friend indeed.", ja: "困った時の友こそ、真の友。", author: "English Proverb"),
        DailyQuote(month: 2, day: 6, en: "Two heads are better than one.", ja: "二人の頭は、一人の頭より良い。", author: "Proverb"),
        DailyQuote(month: 2, day: 7, en: "A candle loses nothing by lighting another candle.", ja: "ろうそくは、他のろうそくに火を灯しても何も失わない。", author: "Proverb"),
        DailyQuote(month: 2, day: 8, en: "Iron sharpens iron.", ja: "鉄は鉄によって研がれる。", author: "Proverb"),
        DailyQuote(month: 2, day: 9, en: "Charity begins at home.", ja: "慈善はまず家庭から始まる。", author: "English Proverb"),
        DailyQuote(month: 2, day: 10, en: "Shared joy is a double joy; shared sorrow is half a sorrow.", ja: "喜びを分かち合えば2倍の喜びに、悲しみを分かち合えば半分の悲しみになる。", author: "Proverb"),
        DailyQuote(month: 2, day: 11, en: "A single arrow is easily broken, but not ten in a bundle.", ja: "一本の矢は簡単に折れるが、十本束ねると折れない。", author: "Japanese Proverb"),
        DailyQuote(month: 2, day: 12, en: "United we stand, divided we fall.", ja: "団結すれば立ち、分裂すれば倒れる。", author: "Proverb"),
        DailyQuote(month: 2, day: 13, en: "Honesty is the best policy.", ja: "正直は最善の策。", author: "English Proverb"),
        DailyQuote(month: 2, day: 14, en: "Love truth, but pardon error.", ja: "真実を愛せ、しかし誤りは許せ。", author: "Voltaire"),
        DailyQuote(month: 2, day: 15, en: "A good friend is a connection to life.", ja: "良き友とは、人生への繋がりである。", author: "Proverb"),
        DailyQuote(month: 2, day: 16, en: "The only way to have a friend is to be one.", ja: "友を持つ唯一の方法は、自分が友になることだ。", author: "Ralph Waldo Emerson"),
        DailyQuote(month: 2, day: 17, en: "Walk beside me and be my friend.", ja: "私の隣を歩いて、友になってほしい。", author: "Proverb"),
        DailyQuote(month: 2, day: 18, en: "It is not the length of life, but the depth of life.", ja: "人生で大切なのは長さではなく、深さである。", author: "Ralph Waldo Emerson"),
        DailyQuote(month: 2, day: 19, en: "Curiosity is the compass of the mind.", ja: "好奇心は、心の羅針盤である。", author: "Proverb"),
        DailyQuote(month: 2, day: 20, en: "He who asks a question is a fool for five minutes; he who does not ask remains a fool forever.", ja: "質問する者は5分間だけ愚か者だが、質問しない者は一生愚か者のままだ。", author: "Proverb"),
        DailyQuote(month: 2, day: 21, en: "Where there is unity, there is strength.", ja: "団結あるところに、力あり。", author: "English Proverb"),
        DailyQuote(month: 2, day: 22, en: "It is never too late to learn.", ja: "学ぶのに、遅すぎるということはない。", author: "English Proverb"),
        DailyQuote(month: 2, day: 23, en: "The more you learn, the more you realize how much you don't know.", ja: "学べば学ぶほど、自分がいかに知らないかを思い知る。", author: "Proverb"),
        DailyQuote(month: 2, day: 24, en: "To teach is to learn twice.", ja: "教えることは、二度学ぶことである。", author: "Joseph Joubert"),
        DailyQuote(month: 2, day: 25, en: "A good name is better than riches.", ja: "良い評判は、富にまさる。", author: "English Proverb"),
        DailyQuote(month: 2, day: 26, en: "Every day is a chance to become better.", ja: "毎日が、より良くなるためのチャンスだ。", author: "Proverb"),
        DailyQuote(month: 2, day: 27, en: "Philosophy begins in wonder.", ja: "哲学は、驚きの中から始まる。", author: "Socrates"),
        DailyQuote(month: 2, day: 28, en: "He who knows others is wise; he who knows himself is enlightened.", ja: "他人を知る者は賢く、自分を知る者は悟っている。", author: "Laozi"),
        DailyQuote(month: 3, day: 1, en: "He who has a why to live can bear with almost any how.", ja: "生きる理由（why）を持つ者は、どんな方法（how）にもほぼ耐えられる。", author: "Nietzsche"),
        DailyQuote(month: 3, day: 2, en: "He conquers who endures.", ja: "耐え抜く者が、最後には勝利を手にする。", author: "Persius"),
        DailyQuote(month: 3, day: 3, en: "You have power over your mind, not outside events. Realize this, and you will find strength.", ja: "あなたは自分の心を制御できる。外の出来事は制御できない。これに気づけば、力を見出せるだろう。", author: "Marcus Aurelius（意訳）"),
        DailyQuote(month: 3, day: 4, en: "Patience is the key to relief.", ja: "忍耐こそが、安らぎへの鍵である。", author: "Arabic Proverb"),
        DailyQuote(month: 3, day: 5, en: "Better safe than sorry.", ja: "後で後悔するより、安全を取れ。", author: "English Proverb"),
        DailyQuote(month: 3, day: 6, en: "It's not what happens to you, but how you react to it that matters.", ja: "大切なのは、何が起こるかではなく、それにどう反応するかだ。", author: "Epictetus（意訳）"),
        DailyQuote(month: 3, day: 7, en: "A good laugh and a long sleep are the best cures.", ja: "よく笑うことと、よく眠ることが、最良の薬である。", author: "Proverb"),
        DailyQuote(month: 3, day: 8, en: "There is no royal road to learning.", ja: "学問に王道なし。", author: "English Proverb"),
        DailyQuote(month: 3, day: 9, en: "Go confidently in the direction of your dreams. Live the life you have imagined.", ja: "自信を持って、自分の夢の方向へ進め。思い描いてきた人生を生きよ。", author: "Henry David Thoreau（意訳）"),
        DailyQuote(month: 3, day: 10, en: "Habits are first cobwebs, then cables.", ja: "習慣は、最初はクモの巣のように弱いが、やがて太い鎖になる。", author: "Spanish Proverb"),
        DailyQuote(month: 3, day: 11, en: "Keep your face always toward the sunshine, and shadows will fall behind you.", ja: "いつも顔を太陽の方に向けていれば、影は後ろに落ちる。", author: "Proverb"),
        DailyQuote(month: 3, day: 12, en: "I am not afraid of storms, for I am learning how to sail my ship.", ja: "私は嵐を恐れない。自分の船の操り方を学んでいるのだから。", author: "Louisa May Alcott"),
        DailyQuote(month: 3, day: 13, en: "No one is useless in this world who lightens the burdens of another.", ja: "誰かの重荷を軽くする人は、この世界で誰一人として無用ではない。", author: "Charles Dickens"),
        DailyQuote(month: 3, day: 14, en: "There is nothing I would not do for those who are really my friends.", ja: "本当の友のためなら、私はどんなことでもするだろう。", author: "Jane Austen"),
        DailyQuote(month: 3, day: 15, en: "The darkest hour is just before the dawn.", ja: "夜明け前が、一番暗い。", author: "English Proverb"),
        DailyQuote(month: 3, day: 16, en: "Everyone thinks of changing the world, but no one thinks of changing himself.", ja: "誰もが世界を変えようと考えるが、自分自身を変えようとは誰も考えない。", author: "Leo Tolstoy"),
        DailyQuote(month: 3, day: 17, en: "To go wrong in one's own way is better than to go right in someone else's.", ja: "他人のやり方で正しく進むより、自分のやり方で間違う方がよい。", author: "Fyodor Dostoevsky"),
        DailyQuote(month: 3, day: 18, en: "All that glitters is not gold.", ja: "光るものすべてが、金とは限らない。", author: "English Proverb"),
        DailyQuote(month: 3, day: 19, en: "Great oaks from little acorns grow.", ja: "大きな樫の木も、小さなどんぐりから育つ。", author: "English Proverb"),
        DailyQuote(month: 3, day: 20, en: "Victory belongs to the most persevering.", ja: "勝利は、最も粘り強く努力した者のものである。", author: "Napoleon Bonaparte"),
        DailyQuote(month: 3, day: 21, en: "I attribute my success to this: I never gave or took any excuse.", ja: "私の成功の理由は、決して言い訳をせず、受け入れもしなかったことだ。", author: "Florence Nightingale"),
        DailyQuote(month: 3, day: 22, en: "Failure is impossible.", ja: "失敗などあり得ない。", author: "Susan B. Anthony"),
        DailyQuote(month: 3, day: 23, en: "If there is no struggle, there is no progress.", ja: "苦闘がなければ、進歩もない。", author: "Frederick Douglass"),
        DailyQuote(month: 3, day: 24, en: "Success is measured not so much by the position one has reached, but by the obstacles overcome.", ja: "成功とは、到達した地位よりも、乗り越えた障害によって測られるものだ。", author: "Booker T. Washington"),
        DailyQuote(month: 3, day: 25, en: "Beauty is in the eye of the beholder.", ja: "美は、見る人の目の中にある。（美的感覚は人それぞれ）", author: "English Proverb"),
        DailyQuote(month: 3, day: 26, en: "The tree that does not bend with the wind will be broken by it.", ja: "風に合わせてしなわない木は、風によって折られてしまう。", author: "German Proverb"),
        DailyQuote(month: 3, day: 27, en: "Better a good friend than a bad relative.", ja: "悪い親戚より、良い友の方がよい。", author: "Proverb"),
        DailyQuote(month: 3, day: 28, en: "One kind word can warm three winter months.", ja: "ひとつの優しい言葉が、冬の3ヶ月間を温めてくれる。", author: "Proverb"),
        DailyQuote(month: 3, day: 29, en: "No matter how far you have gone on a wrong road, turn back.", ja: "間違った道をどれだけ進んでしまっても、引き返せばよい。", author: "Proverb"),
        DailyQuote(month: 3, day: 30, en: "Better bend than break.", ja: "折れるより、曲がる方がよい。", author: "Proverb"),
        DailyQuote(month: 3, day: 31, en: "There is no failure except in no longer trying.", ja: "もはや挑戦しなくなることこそが、唯一の失敗である。", author: "Elbert Hubbard"),
        DailyQuote(month: 4, day: 1, en: "The beginning is the most important part of the work.", ja: "始まりこそ、仕事の中で最も重要な部分である。", author: "Plato"),
        DailyQuote(month: 4, day: 2, en: "A bird in the hand is worth two in the bush.", ja: "手の中の一羽は、藪の中の二羽に値する。（確実なものは不確実なものに勝る）", author: "English Proverb"),
        DailyQuote(month: 4, day: 3, en: "This above all: to thine own self be true.", ja: "何よりも大切なのは、自分自身に忠実であることだ。", author: "William Shakespeare"),
        DailyQuote(month: 4, day: 4, en: "It is better to offer no excuse than a bad one.", ja: "下手な言い訳をするくらいなら、何も言わない方がよい。", author: "George Washington"),
        DailyQuote(month: 4, day: 5, en: "God helps those who help themselves.", ja: "天は自ら助くる者を助く。", author: "English Proverb"),
        DailyQuote(month: 4, day: 6, en: "Waste not, want not.", ja: "無駄をしなければ、不足することもない。", author: "English Proverb"),
        DailyQuote(month: 4, day: 7, en: "A rolling stone gathers no moss.", ja: "転がる石には苔が生えぬ。", author: "English Proverb"),
        DailyQuote(month: 4, day: 8, en: "If I have seen further, it is by standing on the shoulders of giants.", ja: "私がより遠くを見渡せたのだとしたら、それは巨人の肩の上に立っていたからだ。", author: "Isaac Newton"),
        DailyQuote(month: 4, day: 9, en: "Look before you leap.", ja: "跳ぶ前に見よ。", author: "English Proverb"),
        DailyQuote(month: 4, day: 10, en: "In life, there is nothing to be feared, only understood.", ja: "人生において、恐れるべきものは何もない。理解すべきものがあるだけだ。", author: "Marie Curie"),
        DailyQuote(month: 4, day: 11, en: "What comes from the heart, enters the heart.", ja: "心から出たものは、人の心に届く。", author: "Proverb"),
        DailyQuote(month: 4, day: 12, en: "Ask the experienced rather than the learned.", ja: "物知りに聞くより、経験者に聞け。", author: "Proverb"),
        DailyQuote(month: 4, day: 13, en: "A good beginning makes a good ending.", ja: "良い始まりは、良い終わりを生む。", author: "Proverb"),
        DailyQuote(month: 4, day: 14, en: "He who does not advance, goes backward.", ja: "前に進まない者は、後ろに下がる。", author: "Proverb"),
        DailyQuote(month: 4, day: 15, en: "After the game, the king and the pawn go into the same box.", ja: "ゲームが終われば、王も歩も同じ箱に収まる。", author: "Italian Proverb"),
        DailyQuote(month: 4, day: 16, en: "One who wants a rose must respect the thorn.", ja: "バラを求める者は、そのとげを受け入れなければならない。", author: "Proverb"),
        DailyQuote(month: 4, day: 17, en: "A drop of patience is worth more than a bushel of brains.", ja: "一滴の忍耐は、一斗の知恵よりも価値がある。", author: "Proverb"),
        DailyQuote(month: 4, day: 18, en: "Do good and cast it into the sea.", ja: "良いことをしたら、それは海に投げ込んでしまえ。", author: "Proverb"),
        DailyQuote(month: 4, day: 19, en: "Going through hardship is going through a school.", ja: "苦難を経験することは、一つの学校を経験することだ。", author: "Proverb"),
        DailyQuote(month: 4, day: 20, en: "A gem cannot be polished without friction, nor a person perfected without trials.", ja: "摩擦なしに宝石は磨かれず、試練なしに人は成長しない。", author: "Proverb"),
        DailyQuote(month: 4, day: 21, en: "He who does not look back at where he came from will not reach his destination.", ja: "自分が来た場所を振り返らない者は、目的地にたどり着けない。", author: "Proverb"),
        DailyQuote(month: 4, day: 22, en: "He who chases two hares catches neither.", ja: "二羽のウサギを追う者は、どちらも捕まえられない。", author: "Proverb"),
        DailyQuote(month: 4, day: 23, en: "Happiness is a place between too little and too much.", ja: "幸せとは、少なすぎず多すぎずのちょうど良い場所にある。", author: "Proverb"),
        DailyQuote(month: 4, day: 24, en: "There is no such thing as bad weather, only bad clothes.", ja: "悪い天気などというものはなく、あるのは悪い服装だけだ。", author: "Proverb"),
        DailyQuote(month: 4, day: 25, en: "A book is a mute teacher.", ja: "本とは、物言わぬ教師である。", author: "Proverb"),
        DailyQuote(month: 4, day: 26, en: "Waste no more time arguing about what a good person should be. Be one.", ja: "良い人間とはどうあるべきかを議論する時間を、もう無駄にするな。自分がそうなればよい。", author: "Marcus Aurelius"),
        DailyQuote(month: 4, day: 27, en: "The pen is mightier than the sword.", ja: "ペンは剣よりも強し。", author: "English Proverb"),
        DailyQuote(month: 4, day: 28, en: "First say to yourself what you would be, and then do what you have to do.", ja: "まず自分がどうありたいかを自分に言い聞かせよ。それから、すべきことをせよ。", author: "Epictetus"),
        DailyQuote(month: 4, day: 29, en: "So long as there is life in the sick man, it is said that there is hope.", ja: "病人に命がある限り、望みもあると言われる。", author: "Cicero"),
        DailyQuote(month: 4, day: 30, en: "Actions speak louder than words.", ja: "行動は言葉よりも雄弁に語る。", author: "English Proverb"),
        DailyQuote(month: 5, day: 1, en: "When the going gets tough, the tough get going.", ja: "状況が厳しくなったとき、強い者はますます奮起する。", author: "English Proverb"),
        DailyQuote(month: 5, day: 2, en: "You reap what you sow.", ja: "蒔いた種は、自分で刈り取ることになる。", author: "English Proverb"),
        DailyQuote(month: 5, day: 3, en: "Every dog has its day.", ja: "どんな犬にも、その日が来る。（誰にでも活躍のときがある）", author: "English Proverb"),
        DailyQuote(month: 5, day: 4, en: "Birds of a feather flock together.", ja: "類は友を呼ぶ。", author: "English Proverb"),
        DailyQuote(month: 5, day: 5, en: "Wisdom outweighs any wealth.", ja: "知恵は、いかなる富をも上回る。", author: "Sophocles"),
        DailyQuote(month: 5, day: 6, en: "The mind is not a vessel to be filled, but a fire to be kindled.", ja: "心とは、満たされるべき器ではなく、灯されるべき炎である。", author: "Plutarch"),
        DailyQuote(month: 5, day: 7, en: "Nothing is stronger than habit.", ja: "習慣より強いものはない。", author: "Ovid"),
        DailyQuote(month: 5, day: 8, en: "Seize the day, trusting little in tomorrow.", ja: "今日という日をつかめ。明日をあまり当てにせずに。", author: "Horace"),
        DailyQuote(month: 5, day: 9, en: "There's no place like home.", ja: "家に勝る場所はない。", author: "English Proverb"),
        DailyQuote(month: 5, day: 10, en: "The great man is he who does not lose his child's heart.", ja: "偉大な人とは、子どものような心を失わない人のことだ。", author: "Mencius"),
        DailyQuote(month: 5, day: 11, en: "Curiosity killed the cat.", ja: "好奇心は猫をも殺す。（詮索好きは身を滅ぼす）", author: "English Proverb"),
        DailyQuote(month: 5, day: 12, en: "Today is victory over yourself of yesterday.", ja: "今日とは、昨日の自分に勝つことである。", author: "Miyamoto Musashi"),
        DailyQuote(month: 5, day: 13, en: "If you want your dreams to come true, don't sleep.", ja: "夢を叶えたいなら、眠っていてはいけない。", author: "Proverb"),
        DailyQuote(month: 5, day: 14, en: "When spider webs unite, they can tie up a lion.", ja: "クモの巣も集まれば、ライオンをも縛り上げることができる。", author: "Proverb"),
        DailyQuote(month: 5, day: 15, en: "However long the night, the dawn will break.", ja: "夜がどれほど長くても、夜明けはやってくる。", author: "Proverb"),
        DailyQuote(month: 5, day: 16, en: "What is the most important thing in the world? It is people, it is people, it is people.", ja: "この世で最も大切なものは何か。それは人、それは人、それは人である。", author: "Proverb"),
        DailyQuote(month: 5, day: 17, en: "Not all knowledge is found in one place.", ja: "すべての知識が、一つの場所にあるわけではない。", author: "Proverb"),
        DailyQuote(month: 5, day: 18, en: "Tell me and I forget, teach me and I remember, involve me and I learn.", ja: "話してくれれば忘れる。教えてくれれば覚える。参加させてくれれば身につく。", author: "Proverb"),
        DailyQuote(month: 5, day: 19, en: "Repetition is the mother of learning.", ja: "反復は、学びの母である。", author: "Russian Proverb"),
        DailyQuote(month: 5, day: 20, en: "Old men plant trees whose shade they will never sit in.", ja: "老人たちは、自分が座ることのない木陰のために木を植える。", author: "Proverb"),
        DailyQuote(month: 5, day: 21, en: "The wise man keeps his tongue in his heart.", ja: "賢者は、自分の舌を心の中にしまっている。", author: "Proverb"),
        DailyQuote(month: 5, day: 22, en: "A book is like a garden carried in the pocket.", ja: "本とは、ポケットに入れて持ち運べる庭のようなものだ。", author: "Proverb"),
        DailyQuote(month: 5, day: 23, en: "A single spark can start a great fire.", ja: "たった一つの火花が、大きな炎を生むことがある。", author: "Proverb"),
        DailyQuote(month: 5, day: 24, en: "Do not fix your eyes on the road behind others; look at your own road.", ja: "他人の後ろの道ばかり見つめるのではなく、自分自身の道を見よ。", author: "Proverb"),
        DailyQuote(month: 5, day: 25, en: "Because of a mistake, you learn something you did not know before.", ja: "失敗があるからこそ、それまで知らなかったことを学べる。", author: "Proverb"),
        DailyQuote(month: 5, day: 26, en: "Light burdens become heavy if carried far.", ja: "軽い荷物も、遠くまで運べば重くなる。", author: "Proverb"),
        DailyQuote(month: 5, day: 27, en: "It is best to do things in the right order.", ja: "物事は正しい順序で行うのが一番よい。", author: "Proverb"),
        DailyQuote(month: 5, day: 28, en: "He who wants to eat the kernel must crack the nut.", ja: "木の実を食べたいなら、殻を割らなければならない。", author: "Proverb"),
        DailyQuote(month: 5, day: 29, en: "Practice makes the master.", ja: "練習が、達人を作る。", author: "Proverb"),
        DailyQuote(month: 5, day: 30, en: "Work praises the master.", ja: "仕事の出来栄えが、その職人を物語る。", author: "Proverb"),
        DailyQuote(month: 5, day: 31, en: "A guest is a gift, whether they come early or late.", ja: "客人とは贈り物である。早く来ようと遅く来ようと。", author: "Proverb"),
        DailyQuote(month: 6, day: 1, en: "The heart has its reasons which reason does not know.", ja: "心には、理性にはわからない理由がある。", author: "Blaise Pascal"),
        DailyQuote(month: 6, day: 2, en: "It is not enough to have a good mind; the main thing is to use it well.", ja: "良い頭脳を持つだけでは十分ではない。大切なのは、それをうまく使うことだ。", author: "René Descartes"),
        DailyQuote(month: 6, day: 3, en: "It is sometimes said that common sense is very rare.", ja: "常識というものは、実はとても稀なものだとよく言われる。", author: "Voltaire"),
        DailyQuote(month: 6, day: 4, en: "Two wrongs don't make a right.", ja: "二つの過ちは、一つの正しさにはならない。", author: "English Proverb"),
        DailyQuote(month: 6, day: 5, en: "Come forth into the light of things, let Nature be your teacher.", ja: "光の中へ出ておいで。自然をあなたの教師にしよう。", author: "William Wordsworth"),
        DailyQuote(month: 6, day: 6, en: "A thing of beauty is a joy forever.", ja: "美しいものは、永遠の喜びである。", author: "John Keats"),
        DailyQuote(month: 6, day: 7, en: "If winter comes, can spring be far behind?", ja: "冬が来たならば、春は遠くないはずだ。", author: "Percy Bysshe Shelley"),
        DailyQuote(month: 6, day: 8, en: "To strive, to seek, to find, and not to yield.", ja: "努力し、探求し、見出し、そして屈しないこと。", author: "Alfred Lord Tennyson"),
        DailyQuote(month: 6, day: 9, en: "The grass is always greener on the other side.", ja: "隣の芝生は青く見える。", author: "English Proverb"),
        DailyQuote(month: 6, day: 10, en: "Out of sight, out of mind.", ja: "去る者は日々に疎し。（見えなくなれば、忘れられていく）", author: "English Proverb"),
        DailyQuote(month: 6, day: 11, en: "Hope is the thing with feathers that perches in the soul.", ja: "希望とは、羽を持ち、心の中にとまる小鳥のようなものだ。", author: "Emily Dickinson"),
        DailyQuote(month: 6, day: 12, en: "All good things must come to an end.", ja: "すべての良いことには、終わりが来る。", author: "English Proverb"),
        DailyQuote(month: 6, day: 13, en: "Don't put all your eggs in one basket.", ja: "卵を一つのかごに全部盛るな。（危険は分散せよ）", author: "English Proverb"),
        DailyQuote(month: 6, day: 14, en: "Better to fail in originality than to succeed in imitation.", ja: "模倣で成功するより、独創性の中で失敗する方がよい。", author: "Herman Melville"),
        DailyQuote(month: 6, day: 15, en: "I am no bird; and no net ensnares me; I am a free human being with an independent will.", ja: "私は鳥ではない。どんな網も私を捕らえられない。私は、自分の意志を持つ自由な人間だ。", author: "Charlotte Brontë"),
        DailyQuote(month: 6, day: 16, en: "Progress is the law of life.", ja: "前進こそが、人生の法則である。", author: "Robert Browning"),
        DailyQuote(month: 6, day: 17, en: "Absence makes the heart grow fonder.", ja: "離れていると、想いはより募る。", author: "English Proverb"),
        DailyQuote(month: 6, day: 18, en: "No man's knowledge here can go beyond his experience.", ja: "人の知識は、その人の経験を超えることはできない。", author: "John Locke"),
        DailyQuote(month: 6, day: 19, en: "Nature never deceives us; it is we who deceive ourselves.", ja: "自然は決して私たちを欺かない。欺いているのは、私たち自身なのだ。", author: "Jean-Jacques Rousseau"),
        DailyQuote(month: 6, day: 20, en: "Success in the majority of circumstances depends on knowing how long it takes to succeed.", ja: "多くの場合、成功は、成功するまでにどれくらいかかるかを知っているかどうかにかかっている。", author: "Montesquieu"),
        DailyQuote(month: 6, day: 21, en: "A book holds a house of gold.", ja: "一冊の本の中には、黄金の家が眠っている。", author: "Chinese Proverb"),
        DailyQuote(month: 6, day: 22, en: "To know everything is to know nothing.", ja: "すべてを知ることは、何も知らないことに等しい。", author: "French Proverb"),
        DailyQuote(month: 6, day: 23, en: "Listen or your tongue will make you deaf.", ja: "耳を傾けなさい。さもなければ、自分の舌が自分を耳の不自由な者にしてしまう。", author: "Proverb"),
        DailyQuote(month: 6, day: 24, en: "Fortune favors the bold.", ja: "幸運は、勇敢な者に味方する。", author: "Latin Proverb"),
        DailyQuote(month: 6, day: 25, en: "Speak little, do much.", ja: "言葉少なに、多くを為せ。", author: "Spanish Proverb"),
        DailyQuote(month: 6, day: 26, en: "The morning hour has gold in its mouth.", ja: "朝の時間は、口に黄金をくわえている。", author: "German Proverb"),
        DailyQuote(month: 6, day: 27, en: "The clever man is not the one who gets out of a difficulty easily, but who does not get into it.", ja: "賢い人とは、困難から簡単に抜け出せる人ではなく、そもそも困難に陥らない人のことだ。", author: "Arabic Proverb"),
        DailyQuote(month: 6, day: 28, en: "It takes a village to raise a child.", ja: "一人の子どもを育てるには、村ひとつが必要だ。", author: "African Proverb"),
        DailyQuote(month: 6, day: 29, en: "Slow and steady wins the race.", ja: "ゆっくりでも着実な者が、レースに勝つ。", author: "Aesop"),
        DailyQuote(month: 6, day: 30, en: "Practice what you preach.", ja: "自分が説くことを、自ら実行せよ。", author: "English Proverb"),
        DailyQuote(month: 7, day: 1, en: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", ja: "心は、それ自体が一つの場所であり、地獄を天国に、天国を地獄に変えることもできる。", author: "John Milton"),
        DailyQuote(month: 7, day: 2, en: "The early bird catches the worm.", ja: "早起きの鳥は虫を捕まえる。", author: "English Proverb"),
        DailyQuote(month: 7, day: 3, en: "All that we see or seem is but a dream within a dream.", ja: "私たちが見るもの、そう見えるものはすべて、夢の中の夢に過ぎない。", author: "Edgar Allan Poe"),
        DailyQuote(month: 7, day: 4, en: "Great things are done when men and mountains meet.", ja: "偉大なことは、人と山が出会うときに成し遂げられる。", author: "William Blake"),
        DailyQuote(month: 7, day: 5, en: "The best-laid schemes of mice and men often go awry.", ja: "ねずみや人間の最良の計画も、しばしば狂う。", author: "Robert Burns"),
        DailyQuote(month: 7, day: 6, en: "Vision is the art of seeing what is invisible to others.", ja: "先見の明とは、他人には見えないものを見抜く技術である。", author: "Jonathan Swift"),
        DailyQuote(month: 7, day: 7, en: "Fear of danger is ten thousand times more terrifying than danger itself.", ja: "危険への恐れは、危険そのものより一万倍も恐ろしい。", author: "Daniel Defoe"),
        DailyQuote(month: 7, day: 8, en: "Advice is like snow; the softer it falls, the longer it dwells upon the mind.", ja: "助言は雪のようなもの。静かに降るほど、心に長くとどまる。", author: "Samuel Taylor Coleridge"),
        DailyQuote(month: 7, day: 9, en: "If we had no winter, the spring would not be so pleasant.", ja: "もし冬がなければ、春はこれほど心地よくは感じられないだろう。", author: "Anne Bradstreet"),
        DailyQuote(month: 7, day: 10, en: "He that is down needs fear no fall.", ja: "すでに落ちている者は、それ以上落ちることを恐れる必要はない。", author: "John Bunyan"),
        DailyQuote(month: 7, day: 11, en: "Unity is strength, division is weakness.", ja: "団結は力であり、分裂は弱さである。", author: "Proverb"),
        DailyQuote(month: 7, day: 12, en: "However far the stream flows, it never forgets its source.", ja: "小川はどれほど遠くまで流れても、その源を決して忘れない。", author: "Proverb"),
        DailyQuote(month: 7, day: 13, en: "A person is a person through other persons.", ja: "人は、他者を通してこそ人となる。", author: "Zulu Proverb"),
        DailyQuote(month: 7, day: 14, en: "No one shows a child the sky.", ja: "誰も、子どもに空の見方をわざわざ教える必要はない。", author: "Proverb"),
        DailyQuote(month: 7, day: 15, en: "Rain does not fall on one roof alone.", ja: "雨は、一つの屋根だけに降るのではない。", author: "Proverb"),
        DailyQuote(month: 7, day: 16, en: "He who is not courageous enough to take risks will accomplish nothing in life.", ja: "危険を冒す勇気を持たない者は、人生で何も成し遂げられない。", author: "Proverb"),
        DailyQuote(month: 7, day: 17, en: "Do not compare your chapter one with someone else's chapter twenty.", ja: "自分の第1章を、他人の第20章と比べてはいけない。", author: "Proverb"),
        DailyQuote(month: 7, day: 18, en: "Do not throw away the ladder after you have climbed the wall.", ja: "壁を登り終えたからといって、そのはしごを捨ててはいけない。", author: "Proverb"),
        DailyQuote(month: 7, day: 19, en: "A tree is known by its fruit.", ja: "木は、その実によって知られる。", author: "Proverb"),
        DailyQuote(month: 7, day: 20, en: "He who seeks, finds.", ja: "探し求める者は、見つけ出す。", author: "Proverb"),
        DailyQuote(month: 7, day: 21, en: "Ask a wise question, get a wise answer.", ja: "賢い問いを投げかければ、賢い答えが返ってくる。", author: "Proverb"),
        DailyQuote(month: 7, day: 22, en: "A friend's eye is a good mirror.", ja: "友の目は、良き鏡である。", author: "Proverb"),
        DailyQuote(month: 7, day: 23, en: "Even a small bee can sting a big bear.", ja: "小さなハチでも、大きなクマを刺すことができる。", author: "Proverb"),
        DailyQuote(month: 7, day: 24, en: "Knowledge without practice is a tree without fruit.", ja: "実践を伴わない知識は、実をつけない木のようなものだ。", author: "Proverb"),
        DailyQuote(month: 7, day: 25, en: "A single tree does not make a forest.", ja: "一本の木だけでは、森にはならない。", author: "Proverb"),
        DailyQuote(month: 7, day: 26, en: "Be humble, for you are made of earth. Be noble, for you are made of stars.", ja: "謙虚であれ、あなたは土からできているのだから。気高くあれ、あなたは星からできているのだから。", author: "Proverb"),
        DailyQuote(month: 7, day: 27, en: "Little children step on your toes; big children step on your heart.", ja: "小さな子どもは足を踏むが、大きくなった子どもは心を踏む。", author: "Proverb"),
        DailyQuote(month: 7, day: 28, en: "The apple doesn't fall far from the tree.", ja: "リンゴは木から遠くには落ちない。", author: "Proverb"),
        DailyQuote(month: 7, day: 29, en: "Together we are strong; apart we are weak.", ja: "共にいれば私たちは強く、離れていれば弱い。", author: "Proverb"),
        DailyQuote(month: 7, day: 30, en: "Every path has its puddle.", ja: "どんな道にも、水たまりはあるものだ。", author: "Proverb"),
        DailyQuote(month: 7, day: 31, en: "A good word is like a spring rain.", ja: "良い言葉は、春の雨のようなものだ。", author: "Proverb"),
        DailyQuote(month: 8, day: 1, en: "Chance favors the prepared mind.", ja: "幸運は、準備された心に味方する。", author: "Louis Pasteur"),
        DailyQuote(month: 8, day: 2, en: "Don't wait for inspiration; go after it with a club.", ja: "ひらめきを待つのではなく、棍棒を持って追いかけろ。", author: "Jack London"),
        DailyQuote(month: 8, day: 3, en: "Great is the art of beginning, but greater is the art of ending.", ja: "始める技術も偉大だが、終える技術はさらに偉大である。", author: "Henry Wadsworth Longfellow"),
        DailyQuote(month: 8, day: 4, en: "Not failure, but low aim, is crime.", ja: "罪なのは失敗することではなく、目標を低く設定することだ。", author: "James Russell Lowell"),
        DailyQuote(month: 8, day: 5, en: "Little by little does the trick.", ja: "少しずつの積み重ねが、事を成し遂げる。", author: "English Proverb"),
        DailyQuote(month: 8, day: 6, en: "Don't count your chickens before they hatch.", ja: "卵がかえる前からひよこの数を数えるな。（早合点するな）", author: "English Proverb"),
        DailyQuote(month: 8, day: 7, en: "A man who does not think for himself does not think at all.", ja: "自分の頭で考えない者は、まったく考えていないのと同じだ。", author: "English Proverb"),
        DailyQuote(month: 8, day: 8, en: "Every wall is a door.", ja: "どんな壁も、扉になり得る。", author: "Proverb"),
        DailyQuote(month: 8, day: 9, en: "Have something to say, and say it as clearly as you can.", ja: "言うべきことを持て。そして、できる限り明確にそれを言え。", author: "Matthew Arnold"),
        DailyQuote(month: 8, day: 10, en: "What we learn with pleasure we never forget.", ja: "楽しんで学んだことは、決して忘れない。", author: "English Proverb"),
        DailyQuote(month: 8, day: 11, en: "The squeaky wheel gets the grease.", ja: "きしむ車輪ほど、油を差してもらえる。（声を上げる者が注目される）", author: "English Proverb"),
        DailyQuote(month: 8, day: 12, en: "Aim for the moon. If you miss, you may hit a star.", ja: "月を目指せ。外れても、星に届くかもしれない。", author: "English Proverb"),
        DailyQuote(month: 8, day: 13, en: "Be ashamed to die until you have won some victory for humanity.", ja: "人類のために何か勝利を収めるまでは、死ぬことを恥じよ。", author: "Horace Mann"),
        DailyQuote(month: 8, day: 14, en: "Beyond the mountains, more mountains.", ja: "山を越えれば、その先にまた山がある。", author: "Haitian Proverb"),
        DailyQuote(month: 8, day: 15, en: "Time longer than rope.", ja: "時間は、ロープよりも長い。", author: "Proverb"),
        DailyQuote(month: 8, day: 16, en: "The shrimp that falls asleep is carried away by the current.", ja: "眠ってしまったエビは、流れに運ばれていってしまう。", author: "Proverb"),
        DailyQuote(month: 8, day: 17, en: "The mountain does not come to you; you must go to the mountain.", ja: "山はあなたの方には来ない。あなたが山へ行かなければならない。", author: "Proverb"),
        DailyQuote(month: 8, day: 18, en: "However tired you may be, do not lean on a rotten stick.", ja: "どんなに疲れていても、腐った棒に寄りかかってはいけない。", author: "Proverb"),
        DailyQuote(month: 8, day: 19, en: "Speech is silver, but silence is golden.", ja: "雄弁は銀、沈黙は金。", author: "English Proverb"),
        DailyQuote(month: 8, day: 20, en: "Even a small ant can build a big anthill.", ja: "小さなアリでも、大きな蟻塚を築くことができる。", author: "Proverb"),
        DailyQuote(month: 8, day: 21, en: "Knowledge grows when it is shared.", ja: "知識は、分かち合われることで育つ。", author: "Proverb"),
        DailyQuote(month: 8, day: 22, en: "It is easier to know how to speak than to know when to be silent.", ja: "いつ黙るべきかを知るより、どう話すべきかを知る方が簡単だ。", author: "Proverb"),
        DailyQuote(month: 8, day: 23, en: "The buffalo that arrives first drinks the clean water.", ja: "最初に到着した水牛が、きれいな水を飲む。", author: "Proverb"),
        DailyQuote(month: 8, day: 24, en: "The elephant's tusks cannot be hidden in its mouth.", ja: "象の牙は、口の中に隠すことができない。", author: "Proverb"),
        DailyQuote(month: 8, day: 25, en: "Whoever wants makes progress; whoever does not want, offers excuses.", ja: "やりたい者は前進し、やりたくない者は言い訳をする。", author: "Proverb"),
        DailyQuote(month: 8, day: 26, en: "Only those who do nothing make no mistakes.", ja: "何もしない者だけが、間違いを犯さない。", author: "Proverb"),
        DailyQuote(month: 8, day: 27, en: "Everyone is the smith of their own fortune.", ja: "誰もが、自分自身の運命を鍛える鍛冶屋である。", author: "Proverb"),
        DailyQuote(month: 8, day: 28, en: "Small deeds done are better than great deeds planned.", ja: "立派に計画された大きな行いより、実際に行われた小さな行いの方がよい。", author: "Proverb"),
        DailyQuote(month: 8, day: 29, en: "He who wants to eat honey must brave the bee sting.", ja: "蜂蜜を食べたい者は、蜂の一刺しを恐れずに立ち向かわなければならない。", author: "Proverb"),
        DailyQuote(month: 8, day: 30, en: "A kind word is worth more than a rich gift.", ja: "優しい言葉は、高価な贈り物よりも価値がある。", author: "Proverb"),
        DailyQuote(month: 8, day: 31, en: "Every cloud has a silver lining.", ja: "どんな雲にも、銀色の裏地がある。", author: "English Proverb"),
        DailyQuote(month: 9, day: 1, en: "He who conquers himself is the mightiest warrior.", ja: "自分自身に打ち勝つ者こそ、最強の戦士である。", author: "Proverb"),
        DailyQuote(month: 9, day: 2, en: "Penny wise, pound foolish.", ja: "一ペニーを惜しんで、一ポンドを失う。（小さな倹約が大きな損につながる）", author: "English Proverb"),
        DailyQuote(month: 9, day: 3, en: "Not till we are lost do we begin to find ourselves.", ja: "道に迷って初めて、私たちは自分自身を見つけ始める。", author: "Henry David Thoreau"),
        DailyQuote(month: 9, day: 4, en: "What lies behind us and what lies before us are small matters compared to what lies within us.", ja: "私たちの背後にあるものも前方にあるものも、内にあるものに比べれば小さなことだ。", author: "Proverb"),
        DailyQuote(month: 9, day: 5, en: "Few things help an individual more than to place responsibility upon him, and to let him know that you trust him.", ja: "人に責任を与え、信頼していることを伝えること以上に、その人を成長させるものは少ない。", author: "Booker T. Washington"),
        DailyQuote(month: 9, day: 6, en: "Power concedes nothing without a demand. It never did and it never will.", ja: "力は、要求なくして何も譲らない。これまでもそうだったし、これからもそうだろう。", author: "Frederick Douglass"),
        DailyQuote(month: 9, day: 7, en: "Do what you can, with what you have, where you are.", ja: "今いる場所で、今持っているもので、今できることをせよ。", author: "Theodore Roosevelt"),
        DailyQuote(month: 9, day: 8, en: "Simplicity is the ultimate sophistication.", ja: "単純さこそ、究極の洗練である。", author: "Proverb"),
        DailyQuote(month: 9, day: 9, en: "Nothing ventured, nothing gained.", ja: "何も賭けなければ、何も得られない。", author: "English Proverb"),
        DailyQuote(month: 9, day: 10, en: "The happiness of your life depends upon the quality of your thoughts.", ja: "人生の幸福は、あなたの思考の質にかかっている。", author: "Marcus Aurelius"),
        DailyQuote(month: 9, day: 11, en: "It is not that we have a short time to live, but that we waste a lot of it.", ja: "私たちに与えられた時間が短いのではない。その多くを無駄にしているのだ。", author: "Seneca"),
        DailyQuote(month: 9, day: 12, en: "No man is free who is not master of himself.", ja: "自分自身の主人でない者は、誰も自由ではない。", author: "Proverb"),
        DailyQuote(month: 9, day: 13, en: "To be ignorant of what happened before you were born is to be forever a child.", ja: "自分が生まれる前に何が起きたかを知らないことは、いつまでも子どものままでいることだ。", author: "Cicero"),
        DailyQuote(month: 9, day: 14, en: "Know thyself.", ja: "汝自身を知れ。", author: "Delphic Maxim"),
        DailyQuote(month: 9, day: 15, en: "A stitch in time saves nine.", ja: "今日の一針、明日の十針。（早めの対処が後の手間を省く）", author: "English Proverb"),
        DailyQuote(month: 9, day: 16, en: "To thine own self be true.", ja: "何よりもまず、自分自身に忠実であれ。", author: "William Shakespeare"),
        DailyQuote(month: 9, day: 17, en: "Necessity is the mother of invention.", ja: "必要は発明の母である。", author: "English Proverb"),
        DailyQuote(month: 9, day: 18, en: "We know what we are, but know not what we may be.", ja: "私たちは自分が何者かを知っているが、何者になり得るかは知らない。", author: "William Shakespeare"),
        DailyQuote(month: 9, day: 19, en: "Judge a man by his questions rather than his answers.", ja: "人を判断するなら、その答えよりも、その問いによって判断せよ。", author: "Duc de Lévis"),
        DailyQuote(month: 9, day: 20, en: "You can lead a horse to water, but you can't make it drink.", ja: "馬を水辺に連れて行くことはできても、水を飲ませることはできない。", author: "English Proverb"),
        DailyQuote(month: 9, day: 21, en: "Vision without action is a daydream. Action without vision is a nightmare.", ja: "行動を伴わない構想は白昼夢であり、構想を伴わない行動は悪夢である。", author: "Proverb"),
        DailyQuote(month: 9, day: 22, en: "You can't judge a book by its cover.", ja: "本を表紙で判断してはいけない。", author: "English Proverb"),
        DailyQuote(month: 9, day: 23, en: "If you want to go fast, go alone. If you want to go far, go together.", ja: "早く行きたいなら、一人で行け。遠くまで行きたいなら、みんなで行け。", author: "African Proverb"),
        DailyQuote(month: 9, day: 24, en: "A wise man does not need advice, and a fool doesn't take it.", ja: "賢者は助言を必要とせず、愚か者は助言を聞き入れない。", author: "Arabic Proverb"),
        DailyQuote(month: 9, day: 25, en: "Through hardships to the stars.", ja: "苦難を越えて、星々へ。", author: "Latin Proverb"),
        DailyQuote(month: 9, day: 26, en: "Little by little, the camel enters the couscous.", ja: "少しずつ、ラクダはクスクスの中に入っていく。", author: "Proverb"),
        DailyQuote(month: 9, day: 27, en: "A stumble may prevent a fall.", ja: "一度つまずくことが、大きく転ぶことを防いでくれる場合がある。", author: "Proverb"),
        DailyQuote(month: 9, day: 28, en: "The dogs bark, but the caravan moves on.", ja: "犬は吠えるが、隊商は進み続ける。", author: "Proverb"),
        DailyQuote(month: 9, day: 29, en: "The one who does not travel thinks their mother is the best cook.", ja: "旅をしない人は、自分の母親が世界一の料理人だと思い込んでいる。", author: "Proverb"),
        DailyQuote(month: 9, day: 30, en: "The person who wakes up first, sees more of the day.", ja: "最初に目覚める人は、より多くの一日を見ることができる。", author: "Proverb"),
        DailyQuote(month: 10, day: 1, en: "You cannot make an omelette without breaking eggs.", ja: "卵を割らずに、オムレツは作れない。（犠牲なしに物事は成し遂げられない）", author: "English Proverb"),
        DailyQuote(month: 10, day: 2, en: "Nothing can stop the man with the right mental attitude from achieving his goal.", ja: "正しい心構えを持つ者を、その目標達成から止められるものは何もない。", author: "Proverb"),
        DailyQuote(month: 10, day: 3, en: "A house divided against itself cannot stand.", ja: "内部で分裂した家は、立っていられない。", author: "Abraham Lincoln"),
        DailyQuote(month: 10, day: 4, en: "Actions, not words, are the true criterion of attachment.", ja: "言葉ではなく行動こそが、真の愛着の証である。", author: "George Washington"),
        DailyQuote(month: 10, day: 5, en: "Better three hours too soon than a minute too late.", ja: "1分遅れるくらいなら、3時間早い方がよい。", author: "William Shakespeare"),
        DailyQuote(month: 10, day: 6, en: "The greater danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.", ja: "私たちの多くにとって本当に危険なのは、目標が高すぎて届かないことではなく、低すぎて簡単に届いてしまうことだ。", author: "Proverb"),
        DailyQuote(month: 10, day: 7, en: "One never notices what has been done; one can only see what remains to be done.", ja: "すでに成し遂げたことに気づく人はいない。人はただ、残された仕事だけを見るものだ。", author: "Marie Curie"),
        DailyQuote(month: 10, day: 8, en: "Appearances are often deceiving.", ja: "見た目は、しばしば人を欺くものだ。", author: "Aesop"),
        DailyQuote(month: 10, day: 9, en: "A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success.", ja: "もう少しの粘り強さ、もう少しの努力があれば、絶望的に見えた失敗も輝かしい成功に変わることがある。", author: "Elbert Hubbard"),
        DailyQuote(month: 10, day: 10, en: "To play a wrong note is insignificant; to play without passion is inexcusable.", ja: "間違った音を弾くことはささいなことだが、情熱なく弾くことは許されない。", author: "Proverb"),
        DailyQuote(month: 10, day: 11, en: "Nothing is too wonderful to be true.", ja: "あまりにも素晴らしすぎて真実ではない、ということはない。", author: "Michael Faraday"),
        DailyQuote(month: 10, day: 12, en: "A penny saved is a penny earned.", ja: "一ペニーの節約は、一ペニーの稼ぎに等しい。", author: "English Proverb"),
        DailyQuote(month: 10, day: 13, en: "I am seeking, I am striving, I am in it with all my heart.", ja: "私は探し求め、努力し、全身全霊でそれに打ち込んでいる。", author: "Vincent van Gogh"),
        DailyQuote(month: 10, day: 14, en: "Children have more need of models than of critics.", ja: "子どもに必要なのは、批評家よりも手本となる存在だ。", author: "Joseph Joubert"),
        DailyQuote(month: 10, day: 15, en: "To err is human, to forgive divine.", ja: "過ちを犯すのは人間らしいことであり、それを許すのは神々しいことである。", author: "Alexander Pope"),
        DailyQuote(month: 10, day: 16, en: "Reading maketh a full man, conference a ready man, and writing an exact man.", ja: "読書は人を豊かにし、議論は人を機敏にし、著作は人を正確にする。", author: "Francis Bacon"),
        DailyQuote(month: 10, day: 17, en: "Divide each difficulty into as many parts as is feasible.", ja: "それぞれの困難は、できる限り多くの部分に分けよ。", author: "René Descartes"),
        DailyQuote(month: 10, day: 18, en: "A closed mouth catches no flies.", ja: "閉じた口には、ハエも入らない。", author: "Chinese Proverb"),
        DailyQuote(month: 10, day: 19, en: "The reputation of a thousand years may be determined by the conduct of one hour.", ja: "千年の評判は、たった一時間の振る舞いによって決まることがある。", author: "Proverb"),
        DailyQuote(month: 10, day: 20, en: "Even monkeys fall from trees.", ja: "猿も木から落ちる。", author: "Proverb"),
        DailyQuote(month: 10, day: 21, en: "When eating fruit, remember who planted the tree.", ja: "果実を食べるときは、その木を植えた人を思い出しなさい。", author: "Proverb"),
        DailyQuote(month: 10, day: 22, en: "The one who plants a tree, plants hope.", ja: "木を植える人は、希望を植えているのだ。", author: "Proverb"),
        DailyQuote(month: 10, day: 23, en: "Happiness is a direction, not a destination.", ja: "幸せとは、目的地ではなく、進む方向である。", author: "Proverb"),
        DailyQuote(month: 10, day: 24, en: "Better a diamond with a flaw than a pebble without one.", ja: "傷のないただの小石より、傷があってもダイヤモンドの方がよい。", author: "Proverb"),
        DailyQuote(month: 10, day: 25, en: "He who does not know how to smile should not open a shop.", ja: "微笑み方を知らない者は、店を開くべきではない。", author: "Proverb"),
        DailyQuote(month: 10, day: 26, en: "The wolf changes his coat, but not his character.", ja: "オオカミは毛皮を変えても、性格までは変えない。", author: "Proverb"),
        DailyQuote(month: 10, day: 27, en: "A good neighbor is better than a distant friend.", ja: "遠くの友人より、近くの良き隣人の方がよい。", author: "Proverb"),
        DailyQuote(month: 10, day: 28, en: "Little said, soon mended.", ja: "言葉が少なければ、すぐに事は収まる。", author: "Proverb"),
        DailyQuote(month: 10, day: 29, en: "Every beginning is hard.", ja: "どんな始まりも、困難なものだ。", author: "Proverb"),
        DailyQuote(month: 10, day: 30, en: "Small rain lays great dust.", ja: "小さな雨も、大きな砂ぼこりを鎮める。", author: "Proverb"),
        DailyQuote(month: 10, day: 31, en: "Time teaches more than a wise man.", ja: "時は、賢者よりも多くのことを教えてくれる。", author: "Proverb"),
        DailyQuote(month: 11, day: 1, en: "In every walk with nature one receives far more than he seeks.", ja: "自然の中を歩くたび、人は求めていた以上のものを受け取る。", author: "John Muir"),
        DailyQuote(month: 11, day: 2, en: "Every great dream begins with a dreamer.", ja: "あらゆる偉大な夢は、一人の夢見る者から始まる。", author: "Proverb"),
        DailyQuote(month: 11, day: 3, en: "The surest way not to fail is to determine to succeed.", ja: "失敗しない最も確実な方法は、成功すると決意することだ。", author: "Richard Brinsley Sheridan"),
        DailyQuote(month: 11, day: 4, en: "Facts are stubborn things.", ja: "事実とは、頑固なものである。", author: "John Adams"),
        DailyQuote(month: 11, day: 5, en: "The secret of success is constancy of purpose.", ja: "成功の秘訣は、目的の一貫性にある。", author: "Benjamin Disraeli"),
        DailyQuote(month: 11, day: 6, en: "Arise, awake, and stop not until the goal is reached.", ja: "立ち上がれ、目覚めよ、そして目標に達するまで止まるな。", author: "Swami Vivekananda"),
        DailyQuote(month: 11, day: 7, en: "Take only memories, leave only footprints.", ja: "持ち帰るのは思い出だけ、残すのは足跡だけにせよ。", author: "Proverb"),
        DailyQuote(month: 11, day: 8, en: "It is curious that physical courage should be so common and moral courage so rare.", ja: "肉体的な勇気はこれほど普通なのに、道徳的な勇気はこれほど稀なのは不思議だ。", author: "Proverb"),
        DailyQuote(month: 11, day: 9, en: "I contain multitudes.", ja: "私という存在の中には、無数の私がいる。", author: "Walt Whitman"),
        DailyQuote(month: 11, day: 10, en: "Far away in the sunshine are my highest aspirations.", ja: "はるか彼方の日差しの中に、私の最も高い志がある。", author: "Louisa May Alcott"),
        DailyQuote(month: 11, day: 11, en: "Reflect upon your present blessings, of which every man has many; not on your past misfortunes, of which all men have some.", ja: "今ある恵みについて考えよ。誰もが多くの恵みを持っている。過去の不運については考えるな。誰にでも多少の不運はあるのだから。", author: "Charles Dickens"),
        DailyQuote(month: 11, day: 12, en: "It isn't what we say or think that defines us, but what we do.", ja: "私たちを定義するのは、言うことや考えることではなく、行うことだ。", author: "Proverb"),
        DailyQuote(month: 11, day: 13, en: "Nothing is stronger than an idea whose time has come.", ja: "時が来た考えほど、強いものはない。", author: "Proverb"),
        DailyQuote(month: 11, day: 14, en: "A watched pot never boils.", ja: "見つめる鍋は煮えない。（待っていると余計に長く感じる）", author: "English Proverb"),
        DailyQuote(month: 11, day: 15, en: "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason.", ja: "私たちのあらゆる知識は感覚から始まり、悟性へと進み、理性で終わる。", author: "Immanuel Kant"),
        DailyQuote(month: 11, day: 16, en: "He who moves not forward, goes backward.", ja: "前に進まない者は、後ろに下がっているのだ。", author: "Johann Wolfgang von Goethe"),
        DailyQuote(month: 11, day: 17, en: "Impossible is a word to be found only in the dictionary of fools.", ja: "「不可能」という言葉は、愚か者の辞書にしか見つからない。", author: "Napoleon Bonaparte"),
        DailyQuote(month: 11, day: 18, en: "Make hay while the sun shines.", ja: "日が照っているうちに干し草を作れ。（好機を逃すな）", author: "English Proverb"),
        DailyQuote(month: 11, day: 19, en: "Don't cross the bridge until you come to it.", ja: "その橋にたどり着くまでは、渡ろうとするな。（先のことを心配しすぎるな）", author: "English Proverb"),
        DailyQuote(month: 11, day: 20, en: "One generation plants the trees; another gets the shade.", ja: "ある世代が木を植え、別の世代がその木陰を得る。", author: "Proverb"),
        DailyQuote(month: 11, day: 21, en: "The bamboo that bends is stronger than the oak that resists.", ja: "しなる竹は、抵抗するオークよりも強い。", author: "Proverb"),
        DailyQuote(month: 11, day: 22, en: "Don't let yesterday use up too much of today.", ja: "昨日のことに、今日の時間を使いすぎてはいけない。", author: "Proverb"),
        DailyQuote(month: 11, day: 23, en: "A closed hand cannot receive.", ja: "閉じた手は、何も受け取ることができない。", author: "Proverb"),
        DailyQuote(month: 11, day: 24, en: "He who waits achieves.", ja: "待つことができる者は、成し遂げる。", author: "Proverb"),
        DailyQuote(month: 11, day: 25, en: "The river does not flow back.", ja: "川は、逆に流れることはない。", author: "Proverb"),
        DailyQuote(month: 11, day: 26, en: "A friend is a second self.", ja: "友とは、もう一人の自分である。", author: "Proverb"),
        DailyQuote(month: 11, day: 27, en: "Every day is not Christmas.", ja: "毎日がクリスマスというわけではない。", author: "Proverb"),
        DailyQuote(month: 11, day: 28, en: "The hasty person eats the food before it is cooked.", ja: "せっかちな人は、料理ができあがる前に食べてしまう。", author: "Proverb"),
        DailyQuote(month: 11, day: 29, en: "The camel does not see its own hump.", ja: "ラクダは、自分自身のこぶを見ることができない。", author: "Proverb"),
        DailyQuote(month: 11, day: 30, en: "Get advice from everyone, but act with your own mind.", ja: "誰からでも助言を得よ。しかし、行動するときは自分自身の考えに従え。", author: "Proverb"),
        DailyQuote(month: 12, day: 1, en: "Do not fear going slowly; fear only to stand still.", ja: "ゆっくり進むことを恐れるな。恐れるべきは、立ち止まることだけだ。", author: "Proverb"),
        DailyQuote(month: 12, day: 2, en: "Into each life some rain must fall.", ja: "どんな人生にも、いくらかの雨は降らなければならない。", author: "Henry Wadsworth Longfellow"),
        DailyQuote(month: 12, day: 3, en: "The one who doesn't look ahead remains behind.", ja: "先を見ようとしない者は、後ろに取り残される。", author: "Proverb"),
        DailyQuote(month: 12, day: 4, en: "A good listener needs few words.", ja: "よい聞き手には、多くの言葉は必要ない。", author: "Proverb"),
        DailyQuote(month: 12, day: 5, en: "The crab that walks too much loses its claws.", ja: "歩きすぎるカニは、はさみを失ってしまう。", author: "Proverb"),
        DailyQuote(month: 12, day: 6, en: "Do not leave for tomorrow what can be done today.", ja: "今日できることを、明日に残してはいけない。", author: "Proverb"),
        DailyQuote(month: 12, day: 7, en: "He who plants good deeds gathers joy.", ja: "善い行いを植える者は、喜びを刈り取る。", author: "Proverb"),
        DailyQuote(month: 12, day: 8, en: "A single hand cannot clap.", ja: "片手だけでは、拍手はできない。", author: "Proverb"),
        DailyQuote(month: 12, day: 9, en: "A friend is known in time of need.", ja: "友は、困難なときにこそわかるものだ。", author: "Proverb"),
        DailyQuote(month: 12, day: 10, en: "Trees planted by our ancestors give us shade; let us plant for those to come.", ja: "先祖が植えた木々が、私たちに木陰を与えてくれる。次に来る人々のために、私たちも木を植えよう。", author: "Proverb"),
        DailyQuote(month: 12, day: 11, en: "The lizard that jumps from a high tree says it will praise itself if no one else does.", ja: "高い木から飛び降りるトカゲは、誰も褒めてくれないなら自分で自分を褒めようと言う。", author: "Proverb"),
        DailyQuote(month: 12, day: 12, en: "The axe forgets, but the tree remembers.", ja: "斧は忘れても、木は覚えている。", author: "Proverb"),
        DailyQuote(month: 12, day: 13, en: "A grateful person receives more.", ja: "感謝する人は、より多くを受け取る。", author: "Proverb"),
        DailyQuote(month: 12, day: 14, en: "If you can walk, you can dance; if you can talk, you can sing.", ja: "歩けるなら、踊ることもできる。話せるなら、歌うこともできる。", author: "Proverb"),
        DailyQuote(month: 12, day: 15, en: "Wood already touched by fire is not hard to set alight.", ja: "すでに火に触れたことのある木は、再び燃やすのは難しくない。", author: "Proverb"),
        DailyQuote(month: 12, day: 16, en: "A single bracelet does not jingle.", ja: "一つだけの腕輪は、音を立てない。", author: "Proverb"),
        DailyQuote(month: 12, day: 17, en: "Knowledge is like a garden: if it is not cultivated, it cannot be harvested.", ja: "知識とは庭のようなもの。手入れをしなければ、実りを得ることはできない。", author: "Proverb"),
        DailyQuote(month: 12, day: 18, en: "It is the tree that stands alone that fears the wind.", ja: "風を恐れるのは、一本だけで立つ木である。", author: "Proverb"),
        DailyQuote(month: 12, day: 19, en: "When the music changes, so does the dance.", ja: "音楽が変われば、踊りも変わる。", author: "Proverb"),
        DailyQuote(month: 12, day: 20, en: "A single stick may smoke, but it will not burn.", ja: "一本の薪は煙を出すことはあっても、燃え上がることはない。", author: "Proverb"),
        DailyQuote(month: 12, day: 21, en: "The path to the well-known place is never long.", ja: "よく知っている場所への道は、決して長く感じない。", author: "Proverb"),
        DailyQuote(month: 12, day: 22, en: "You never test the depth of a river with both feet.", ja: "川の深さを、両足で確かめることは決してしない。", author: "Proverb"),
        DailyQuote(month: 12, day: 23, en: "A big ship needs deep water.", ja: "大きな船には、深い水が必要だ。", author: "Proverb"),
        DailyQuote(month: 12, day: 24, en: "The ocean is not filled by one river alone.", ja: "海は、一本の川だけで満たされるのではない。", author: "Proverb"),
        DailyQuote(month: 12, day: 25, en: "Every canoe needs many paddlers.", ja: "どんなカヌーにも、大勢の漕ぎ手が必要だ。", author: "Proverb"),
        DailyQuote(month: 12, day: 26, en: "A single wave does not make the ocean.", ja: "一つの波だけでは、海にはならない。", author: "Proverb"),
        DailyQuote(month: 12, day: 27, en: "Even a small path, if walked daily, becomes a road.", ja: "小さな小道でも、毎日歩けば大きな道になる。", author: "Proverb"),
        DailyQuote(month: 12, day: 28, en: "A guest for one day sees more than the host in a year.", ja: "一日だけの客人は、一年住む主人よりも多くを見る。", author: "Proverb"),
        DailyQuote(month: 12, day: 29, en: "The one who learns a new language gains a new soul.", ja: "新しい言語を学ぶ者は、新しい魂を得る。", author: "Proverb"),
        DailyQuote(month: 12, day: 30, en: "A single coconut can start a whole grove.", ja: "たった一つのココナッツが、一つの林全体の始まりになることがある。", author: "Proverb"),
        DailyQuote(month: 12, day: 31, en: "An ounce of prevention is worth a pound of cure.", ja: "一オンスの予防は、一ポンドの治療に値する。", author: "Benjamin Franklin"),
    ]

    static func quote(for date: Date = Date()) -> DailyQuote {
        let cal = Calendar.current
        let month = cal.component(.month, from: date)
        let day = cal.component(.day, from: date)
        if let exact = quotes.first(where: { $0.month == month && $0.day == day }) {
            return exact
        }
        if month == 2 && day == 29, let leapFallback = quotes.first(where: { $0.month == 2 && $0.day == 28 }) {
            return leapFallback
        }
        return quotes.first!
    }
}
